import QRCode from "qrcode";
import { TICKET_TYPE_LABELS, TicketType } from "../../../shared/types";
import { getInvitationTemplate, getInvitationTemplateLayout, parseInvitationLayout, type InvitationLayer, type InvitationTemplateId } from "./invitationDesign";

export type InvitationPngInput = { fullName: string; idNumber: string; qrCode: string; ticketType: string; seatNumber?: string | null; ceremonyTitle: string; ceremonySubtitle: string; templateId?: InvitationTemplateId | string | null; brandColor?: string | null; logoUrl?: string | null; invitationBackgroundUrl?: string | null; invitationDate?: string | null; invitationVenue?: string | null; invitationDressCode?: string | null; invitationLayout?: string | null };
type Palette = { accent: string; ink: string; muted: string; panel: string; line: string; light: boolean };

function roundedRect(ctx: CanvasRenderingContext2D, x: number, y: number, width: number, height: number, radius: number) { const r = Math.min(radius, width / 2, height / 2); ctx.beginPath(); ctx.moveTo(x + r, y); ctx.arcTo(x + width, y, x + width, y + height, r); ctx.arcTo(x + width, y + height, x, y + height, r); ctx.arcTo(x, y + height, x, y, r); ctx.arcTo(x, y, x + width, y, r); ctx.closePath(); }
function text(ctx: CanvasRenderingContext2D, value: string, x: number, y: number, options: { size: number; color: string; weight?: number; align?: CanvasTextAlign; maxWidth?: number; fontFamily?: string }) { ctx.save(); ctx.direction = "rtl"; ctx.textAlign = options.align ?? "right"; ctx.textBaseline = "middle"; ctx.fillStyle = options.color; ctx.font = `${options.weight ?? 400} ${options.size}px ${options.fontFamily || "Tajawal"}, Cairo, Arial, sans-serif`; ctx.fillText(value, x, y, options.maxWidth); ctx.restore(); }
function loadImage(url?: string | null) { if (!url) return Promise.resolve<HTMLImageElement | null>(null); return new Promise<HTMLImageElement | null>((resolve) => { const image = new Image(); image.crossOrigin = "anonymous"; image.onload = () => resolve(image); image.onerror = () => resolve(null); image.src = url; }); }
function cover(ctx: CanvasRenderingContext2D, image: HTMLImageElement) { const scale = Math.max(1200 / image.width, 1500 / image.height); const width = image.width * scale; const height = image.height * scale; ctx.drawImage(image, (1200 - width) / 2, (1500 - height) / 2, width, height); }
function detailLine(input: InvitationPngInput) { return [["التاريخ", input.invitationDate], ["المكان", input.invitationVenue], ["اللباس", input.invitationDressCode]].filter((entry): entry is [string, string] => Boolean(entry[1]?.trim())).map(([key, value]) => `${key}: ${value}`).join("  •  "); }
function drawDetails(ctx: CanvasRenderingContext2D, input: InvitationPngInput, x: number, y: number, palette: Palette) { const value = detailLine(input); if (!value) return; ctx.fillStyle = palette.light ? "rgba(255,255,255,.62)" : "rgba(5,10,17,.42)"; roundedRect(ctx, x - 400, y - 25, 800, 50, 25); ctx.fill(); text(ctx, value, x, y, { size: 17, color: palette.ink, weight: 700, align: "center", maxWidth: 740 }); }
function drawGuestCard(ctx: CanvasRenderingContext2D, input: InvitationPngInput, x: number, y: number, width: number, palette: Palette) { const rows = [["اسم الضيف الكريم", input.fullName || "ضيف"], ["رقم الهوية", input.idNumber || "—"], ["فئة الدعوة", TICKET_TYPE_LABELS[input.ticketType as TicketType] ?? input.ticketType], ["رقم المقعد", input.seatNumber ? `مقعد (${input.seatNumber})` : "دعوة عامة"]]; const rowHeight = width < 760 ? 54 : 63; const height = rows.length * rowHeight + 42; ctx.fillStyle = palette.panel; roundedRect(ctx, x, y, width, height, 26); ctx.fill(); ctx.strokeStyle = palette.light ? `${palette.accent}99` : "rgba(255,255,255,.28)"; ctx.lineWidth = 1.5; ctx.stroke(); rows.forEach(([label, value], index) => { const rowY = y + 34 + index * rowHeight; text(ctx, label, x + width - 25, rowY, { size: width < 760 ? 17 : 21, color: palette.muted }); text(ctx, value, x + 26, rowY, { size: width < 760 ? 18 : 24, color: palette.ink, weight: 800, align: "left", maxWidth: width * .55 }); if (index < rows.length - 1) { ctx.strokeStyle = palette.line; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(x + 24, rowY + rowHeight / 2 - 1); ctx.lineTo(x + width - 24, rowY + rowHeight / 2 - 1); ctx.stroke(); } }); }
async function qrCanvas(code: string) { const canvas = document.createElement("canvas"); await QRCode.toCanvas(canvas, code, { width: 205, margin: 1, color: { dark: "#0d1322", light: "#fff" } }); return canvas; }
function drawQrCard(ctx: CanvasRenderingContext2D, qr: HTMLCanvasElement, x: number, y: number, size: number, palette: Palette) { ctx.fillStyle = "#fffdf7"; roundedRect(ctx, x, y, size + 32, size + 32, 20); ctx.fill(); ctx.strokeStyle = `${palette.accent}bb`; ctx.lineWidth = 2; ctx.stroke(); ctx.drawImage(qr, x + 16, y + 16, size, size); }
function backgroundGradient(ctx: CanvasRenderingContext2D, templateId: string) { const gradient = ctx.createLinearGradient(0, 0, 1200, 1500); const colors: Record<string, [string, string]> = { royal: ["#241708", "#080909"], minimal: ["#fffefb", "#ddd5c9"], modern: ["#081b38", "#43205b"], luxury: ["#0d3a31", "#061815"], floral: ["#6b2444", "#250d21"], midnight: ["#0d1930", "#050812"], pearl: ["#faf4ec", "#cfbda9"], aurora: ["#0b2951", "#552461"], sapphire: ["#12376a", "#07142e"], rose: ["#7b2c53", "#240d20"], obsidian: ["#29292e", "#030304"], artdeco: ["#1f2135", "#090a11"], celestial: ["#152a56", "#0b1028"], heritage: ["#efe2c8", "#b59362"], cinema: ["#42132c", "#120915"] }; const [start, end] = colors[templateId] || ["#1c2230", "#0a0e16"]; gradient.addColorStop(0, start); gradient.addColorStop(1, end); return gradient; }

function drawStructure(ctx: CanvasRenderingContext2D, layout: string, palette: Palette, drawLogo: (x: number, y: number, size?: number) => void) {
  const border = (radius = 40) => { ctx.strokeStyle = palette.accent; ctx.lineWidth = 4; roundedRect(ctx, 36, 36, 1128, 1428, radius); ctx.stroke(); };
  if (layout === "arch") { border(58); ctx.strokeStyle = `${palette.accent}cc`; ctx.lineWidth = 5; ctx.beginPath(); ctx.moveTo(215, 665); ctx.lineTo(215, 365); ctx.arcTo(215, 150, 600, 150, 385); ctx.arcTo(985, 150, 985, 365, 385); ctx.lineTo(985, 665); ctx.stroke(); drawLogo(555, 285, 90); text(ctx, "دعوة إلى لحظة استثنائية", 600, 245, { size: 21, color: palette.accent, weight: 900, align: "center" }); }
  else if (layout === "marble") { border(24); ctx.strokeStyle = `${palette.accent}70`; ctx.lineWidth = 3; for (let index = 0; index < 6; index++) { ctx.beginPath(); ctx.moveTo(-80, 180 + index * 230); ctx.bezierCurveTo(320, 90 + index * 250, 780, 350 + index * 180, 1280, 150 + index * 235); ctx.stroke(); } text(ctx, "ATELIER INVITATION", 600, 145, { size: 18, color: palette.accent, weight: 900, align: "center" }); drawLogo(555, 470, 90); }
  else if (layout === "poster") { ctx.save(); ctx.globalAlpha = .18; ctx.fillStyle = palette.accent; ctx.beginPath(); ctx.moveTo(0, 0); ctx.lineTo(760, 0); ctx.lineTo(1200, 660); ctx.lineTo(1200, 0); ctx.closePath(); ctx.fill(); ctx.restore(); border(12); text(ctx, "THE", 105, 145, { size: 74, color: palette.accent, weight: 900, align: "left" }); text(ctx, "MOMENT", 105, 230, { size: 74, color: palette.accent, weight: 900, align: "left" }); drawLogo(965, 90, 90); }
  else if (layout === "gallery") { border(42); ctx.save(); ctx.globalAlpha = .2; ctx.fillStyle = palette.accent; roundedRect(ctx, 85, 95, 365, 470, 30); ctx.fill(); roundedRect(ctx, 760, 95, 355, 265, 30); ctx.fill(); roundedRect(ctx, 790, 400, 325, 165, 30); ctx.fill(); ctx.restore(); text(ctx, "COLLECTION", 100, 145, { size: 18, color: palette.accent, weight: 900, align: "left" }); drawLogo(925, 155, 90); }
  else if (layout === "halo") { const halo = ctx.createRadialGradient(600, 325, 50, 600, 325, 490); halo.addColorStop(0, `${palette.accent}77`); halo.addColorStop(.45, `${palette.accent}20`); halo.addColorStop(1, "transparent"); ctx.fillStyle = halo; ctx.fillRect(0, 0, 1200, 820); ctx.strokeStyle = `${palette.accent}77`; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(600, 325, 230, 0, Math.PI * 2); ctx.stroke(); ctx.beginPath(); ctx.arc(600, 325, 300, 0, Math.PI * 2); ctx.stroke(); border(50); drawLogo(555, 130, 90); }
  else if (layout === "split") { ctx.fillStyle = "rgba(3,9,23,.58)"; ctx.fillRect(0, 0, 410, 1500); ctx.fillStyle = palette.accent; ctx.fillRect(390, 90, 7, 1320); text(ctx, "EVENT", 205, 150, { size: 24, color: palette.accent, weight: 900, align: "center" }); drawLogo(160, 205, 90); }
  else if (layout === "ribbon") { border(42); ctx.fillStyle = palette.accent; roundedRect(ctx, 0, 95, 680, 92, 0); ctx.fill(); text(ctx, "دعوة احتفالية", 580, 140, { size: 28, color: "#2b1724", weight: 900 }); drawLogo(920, 100, 90); }
  else if (layout === "formal") { border(8); ctx.fillStyle = "rgba(5,13,28,.66)"; ctx.fillRect(0, 0, 1200, 270); text(ctx, "EXCLUSIVE EVENT", 600, 95, { size: 19, color: palette.accent, weight: 900, align: "center" }); drawLogo(80, 85, 90); }
  else { border(42); drawLogo(555, 75, 90); }
}

function drawFamilyContent(ctx: CanvasRenderingContext2D, family: string, input: InvitationPngInput, layout: ReturnType<typeof getInvitationTemplateLayout>, palette: Palette, qr: HTMLCanvasElement) {
  const title = () => text(ctx, input.ceremonyTitle, layout.titleX, layout.titleY, { size: layout.titleSize, color: layout.titleColor || palette.ink, weight: 900, align: "center", maxWidth: 930, fontFamily: layout.titleFont });
  const subtitle = () => text(ctx, input.ceremonySubtitle, layout.subtitleX, layout.subtitleY, { size: layout.subtitleSize, color: layout.subtitleColor || palette.muted, align: "center", maxWidth: 880, fontFamily: layout.subtitleFont });
  const details = () => drawDetails(ctx, input, layout.detailsX, layout.detailsY, palette);
  const guest = (x = layout.guestX, y = layout.guestY, width = layout.guestWidth) => drawGuestCard(ctx, input, x, y, width, palette);
  const qrCode = (x = layout.qrX, y = layout.qrY, size = layout.qrSize) => drawQrCard(ctx, qr, x, y, size, palette);
  if (family === "ticket") { ctx.save(); ctx.fillStyle = "rgba(4,10,27,.70)"; roundedRect(ctx, 64, 720, 1072, 630, 38); ctx.fill(); ctx.setLineDash([18, 12]); ctx.strokeStyle = `${palette.accent}aa`; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(85, 1135); ctx.lineTo(1115, 1135); ctx.stroke(); ctx.restore(); title(); subtitle(); details(); guest(145, 770, 910); qrCode(110, 1175, 150); text(ctx, "ADMIT ONE", 1050, 1210, { size: 28, color: palette.accent, weight: 900, align: "right" }); text(ctx, input.qrCode, 1050, 1262, { size: 19, color: palette.muted, align: "right" }); }
  else if (family === "magazine") { text(ctx, "THE EVENT EDIT", 1070, 125, { size: 19, color: palette.accent, weight: 900, align: "right" }); text(ctx, input.ceremonyTitle, 1060, layout.titleY, { size: Math.max(layout.titleSize + 12, 58), color: layout.titleColor || palette.ink, weight: 900, maxWidth: 760, fontFamily: layout.titleFont }); text(ctx, input.ceremonySubtitle, 1060, layout.subtitleY, { size: layout.subtitleSize, color: layout.subtitleColor || palette.muted, maxWidth: 700, fontFamily: layout.subtitleFont }); details(); ctx.fillStyle = `${palette.accent}cc`; ctx.fillRect(100, layout.detailsY + 58, 720, 5); guest(105, 795, 700); qrCode(850, 1000, 205); text(ctx, "ISSUE · 2026", 1060, 1370, { size: 19, color: palette.accent, weight: 900, align: "right" }); }
  else if (family === "postcard") { ctx.fillStyle = "rgba(255,255,255,.13)"; roundedRect(ctx, 78, 610, 1044, 650, 28); ctx.fill(); ctx.strokeStyle = `${palette.accent}a6`; ctx.lineWidth = 2; ctx.stroke(); title(); subtitle(); details(); ctx.strokeStyle = `${palette.accent}85`; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(600, 665); ctx.lineTo(600, 1200); ctx.stroke(); guest(640, 735, 435); qrCode(145, 785, 230); text(ctx, "تحية من هذه المناسبة", 360, 1080, { size: 23, color: palette.ink, weight: 800, align: "center", maxWidth: 360 }); }
  else if (family === "vip") { ctx.fillStyle = "rgba(2,6,15,.70)"; roundedRect(ctx, 58, 350, 1084, 760, 42); ctx.fill(); ctx.strokeStyle = `${palette.accent}cc`; ctx.lineWidth = 2; ctx.stroke(); text(ctx, "VIP ACCESS", 1060, 410, { size: 28, color: palette.accent, weight: 900, align: "right" }); text(ctx, input.ceremonyTitle, 1050, layout.titleY, { size: layout.titleSize, color: layout.titleColor || palette.ink, weight: 900, maxWidth: 800, fontFamily: layout.titleFont }); text(ctx, input.ceremonySubtitle, 1050, layout.subtitleY, { size: layout.subtitleSize, color: layout.subtitleColor || palette.muted, maxWidth: 760, fontFamily: layout.subtitleFont }); details(); qrCode(115, 500, 205); guest(380, 520, 690); for (let x = 120; x < 1060; x += 19) { ctx.fillStyle = `${palette.accent}99`; ctx.fillRect(x, 1040, 8, 48); } text(ctx, "PRIVATE INVITATION", 600, 1200, { size: 20, color: palette.muted, align: "center" }); }
  else if (family === "tall-ticket") { ctx.fillStyle = palette.light ? "rgba(255,255,255,.70)" : "rgba(2,7,15,.62)"; roundedRect(ctx, 190, 400, 820, 880, 55); ctx.fill(); ctx.strokeStyle = `${palette.accent}c7`; ctx.lineWidth = 3; ctx.stroke(); title(); subtitle(); details(); ctx.setLineDash([12, 10]); ctx.beginPath(); ctx.moveTo(235, 870); ctx.lineTo(965, 870); ctx.stroke(); ctx.setLineDash([]); guest(245, 610, 710); qrCode(485, 930, 190); text(ctx, "PRESENT THIS PASS", 600, 1210, { size: 18, color: palette.accent, weight: 900, align: "center" }); }
  else if (family === "split") { text(ctx, "EVENT", 205, 150, { size: 24, color: palette.accent, weight: 900, align: "center" }); text(ctx, input.ceremonyTitle, layout.titleX, layout.titleY, { size: layout.titleSize, color: layout.titleColor || palette.ink, weight: 900, maxWidth: 650, fontFamily: layout.titleFont }); text(ctx, input.ceremonySubtitle, layout.subtitleX, layout.subtitleY, { size: layout.subtitleSize, color: layout.subtitleColor || palette.muted, maxWidth: 640, fontFamily: layout.subtitleFont }); details(); guest(470, 470, 640); qrCode(88, 1040, 220); text(ctx, "رمز التحقق", 205, 1300, { size: 20, color: palette.muted, align: "center" }); }
  else if (family === "stage") { ctx.fillStyle = "rgba(10,2,7,.58)"; roundedRect(ctx, 70, 560, 1060, 645, 28); ctx.fill(); text(ctx, "PROGRAMME", 600, 145, { size: 21, color: palette.accent, weight: 900, align: "center" }); title(); subtitle(); details(); text(ctx, "الفقرة الرئيسية", 1040, 640, { size: 19, color: palette.accent, weight: 900, align: "right" }); text(ctx, "يفتح الباب قبل بدء الحفل بـ 30 دقيقة", 1040, 690, { size: 18, color: palette.muted, align: "right" }); guest(145, 760, 910); qrCode(495, 1130, 200); }
  else if (family === "ribbon") { title(); subtitle(); details(); guest(130, 555, 940); qrCode(120, 1030, 210); ctx.fillStyle = "rgba(7,12,20,.50)"; roundedRect(ctx, 385, 1030, 685, 242, 28); ctx.fill(); text(ctx, "رمز التحقق", 1025, 1100, { size: 25, color: palette.muted }); text(ctx, "امسح الرمز عند البوابة لتأكيد الحضور", 1025, 1150, { size: 20, color: palette.ink, weight: 800, maxWidth: 600 }); }
  else if (family === "editorial") { text(ctx, "دعوة خاصة", 1060, 110, { size: 24, color: palette.accent, weight: 900, align: "right" }); text(ctx, input.ceremonyTitle, 1060, layout.titleY, { size: layout.titleSize, color: layout.titleColor || palette.ink, weight: 900, maxWidth: 760, fontFamily: layout.titleFont }); text(ctx, input.ceremonySubtitle, 1060, layout.subtitleY, { size: layout.subtitleSize, color: layout.subtitleColor || palette.muted, maxWidth: 760, fontFamily: layout.subtitleFont }); ctx.fillStyle = palette.accent; ctx.fillRect(100, 465, 700, 5); details(); guest(100, 645, 690); qrCode(840, 1020, 210); }
  else { title(); subtitle(); details(); guest(); qrCode(); }
  text(ctx, "امسح رمز QR لتأكيد الحضور", 600, 1405, { size: 18, color: palette.muted, align: "center" });
}

function layerTextValue(layer: InvitationLayer, input: InvitationPngInput) { return (layer.text || "").replace("{{title}}", input.ceremonyTitle).replace("{{subtitle}}", input.ceremonySubtitle).replace("{{qr}}", input.qrCode); }
function drawLayerShape(ctx: CanvasRenderingContext2D, layer: InvitationLayer) {
  const radius = layer.borderRadius || 0; const background = layer.backgroundColor || "rgba(5,10,18,.45)"; const border = layer.borderColor || "#e8c66d"; ctx.save(); ctx.globalAlpha = (layer.opacity ?? 100) / 100; ctx.fillStyle = background; ctx.strokeStyle = border; ctx.lineWidth = 2;
  if (layer.shape === "circle") { ctx.beginPath(); ctx.ellipse(layer.x + layer.width / 2, layer.y + layer.height / 2, layer.width / 2, layer.height / 2, 0, 0, Math.PI * 2); if (background !== "transparent") ctx.fill(); ctx.stroke(); }
  else if (layer.shape === "arch") { ctx.beginPath(); ctx.moveTo(layer.x, layer.y + layer.height); ctx.lineTo(layer.x, layer.y + layer.height / 2); ctx.arc(layer.x + layer.width / 2, layer.y + layer.height / 2, layer.width / 2, Math.PI, 0); ctx.lineTo(layer.x + layer.width, layer.y + layer.height); if (background !== "transparent") ctx.fill(); ctx.stroke(); }
  else if (layer.shape === "divider") { ctx.fillRect(layer.x, layer.y, layer.width, Math.max(2, layer.height)); }
  else if (layer.shape === "ribbon") { ctx.beginPath(); ctx.moveTo(layer.x, layer.y); ctx.lineTo(layer.x + layer.width, layer.y); ctx.lineTo(layer.x + layer.width - 55, layer.y + layer.height / 2); ctx.lineTo(layer.x + layer.width, layer.y + layer.height); ctx.lineTo(layer.x, layer.y + layer.height); ctx.closePath(); ctx.fill(); }
  else if (layer.shape === "barcode") { for (let cursor = layer.x; cursor < layer.x + layer.width; cursor += 19) ctx.fillRect(cursor, layer.y, 8, layer.height); }
  else { roundedRect(ctx, layer.x, layer.y, layer.width, layer.height, layer.shape === "ticket" ? Math.max(28, radius) : radius); ctx.fill(); ctx.stroke(); if (layer.shape === "ticket") { ctx.setLineDash([16, 12]); ctx.beginPath(); ctx.moveTo(layer.x + 25, layer.y + layer.height * .7); ctx.lineTo(layer.x + layer.width - 25, layer.y + layer.height * .7); ctx.stroke(); ctx.setLineDash([]); } }
  ctx.restore();
}
async function drawInvitationLayers(ctx: CanvasRenderingContext2D, layers: InvitationLayer[], input: InvitationPngInput, palette: Palette, qr: HTMLCanvasElement) {
  for (const layer of [...layers].filter((item) => item.visible !== false).sort((a, b) => a.z - b.z)) {
    ctx.save(); ctx.globalAlpha = (layer.opacity ?? 100) / 100;
    if (layer.kind === "shape") drawLayerShape(ctx, layer);
    if (layer.kind === "text") { const lines = layerTextValue(layer, input).split("\n"); const gap = (layer.fontSize || 26) * 1.08; lines.forEach((line, index) => text(ctx, line, layer.x + layer.width / 2, layer.y + layer.height / 2 + (index - (lines.length - 1) / 2) * gap, { size: layer.fontSize || 26, color: layer.color || palette.ink, weight: 900, align: "center", maxWidth: layer.width, fontFamily: layer.font })); }
    if (layer.kind === "details") drawDetails(ctx, input, layer.x + layer.width / 2, layer.y + layer.height / 2, palette);
    if (layer.kind === "guest") drawGuestCard(ctx, input, layer.x, layer.y, layer.width, palette);
    if (layer.kind === "qr") drawQrCard(ctx, qr, layer.x, layer.y, Math.max(90, Math.min(layer.width, layer.height) - 32), palette);
    if (layer.kind === "image") { const image = await loadImage(layer.imageUrl === "{{logo}}" ? input.logoUrl : layer.imageUrl); if (image) { ctx.save(); roundedRect(ctx, layer.x, layer.y, layer.width, layer.height, layer.borderRadius || 16); ctx.clip(); ctx.drawImage(image, layer.x, layer.y, layer.width, layer.height); ctx.restore(); } }
    ctx.restore();
  }
}

/** يصدر كل قالب ببنية مستقلة، ثم يطبق فوقها أي مواضع محفوظة من محرر القالب. */
export async function createInvitationPngBlob(input: InvitationPngInput): Promise<Blob> {
  if (document.fonts?.ready) await document.fonts.ready;
  const canvas = document.createElement("canvas"); canvas.width = 1200; canvas.height = 1500; const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("لا يمكن إنشاء مساحة رسم الدعوة");
  const template = getInvitationTemplate(input.templateId); const templateLayout = String(template.layout); const light = ["minimal", "pearl", "heritage"].includes(template.id); const palette: Palette = { accent: input.brandColor || template.accent, ink: light ? "#182031" : "#fbfcff", muted: light ? "#4b5b6b" : "#d6dce7", panel: light ? "rgba(255,255,255,.78)" : "rgba(7,13,22,.60)", line: light ? "rgba(24,32,49,.16)" : "rgba(255,255,255,.18)", light };
  const saved = parseInvitationLayout(input.invitationLayout); const layout = saved.sourceTemplateId === template.id && saved.layers?.length ? saved : getInvitationTemplateLayout(template.id);
  ctx.fillStyle = backgroundGradient(ctx, template.id); ctx.fillRect(0, 0, 1200, 1500); const background = await loadImage(input.invitationBackgroundUrl || template.artUrl); if (background) { ctx.save(); ctx.globalAlpha = .72; cover(ctx, background); ctx.restore(); const overlay = ctx.createLinearGradient(0, 0, 0, 1500); overlay.addColorStop(0, light ? "rgba(255,255,255,.22)" : "rgba(2,7,13,.43)"); overlay.addColorStop(.5, "rgba(2,7,13,.22)"); overlay.addColorStop(1, "rgba(2,7,13,.66)"); ctx.fillStyle = overlay; ctx.fillRect(0, 0, 1200, 1500); }
  const qr = await qrCanvas(input.qrCode); const logo = await loadImage(input.logoUrl); const drawLogo = (x: number, y: number, size = 90) => { if (!logo) return; ctx.save(); roundedRect(ctx, x, y, size, size, 16); ctx.clip(); ctx.drawImage(logo, x, y, size, size); ctx.restore(); };
  if (!layout.layers?.length) drawStructure(ctx, templateLayout, palette, drawLogo);
  const adjustedPalette = { ...palette, panel: light ? `rgba(255,255,255,${Math.max(.35, layout.panelOpacity / 100)})` : `rgba(7,13,22,${Math.max(.25, layout.panelOpacity / 100)})` };
  if (layout.layers?.length) await drawInvitationLayers(ctx, layout.layers, input, adjustedPalette, qr); else drawFamilyContent(ctx, String(template.family), input, layout, adjustedPalette, qr);
  const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png")); if (!blob) throw new Error("تعذر إنشاء ملف PNG"); return blob;
}
