CREATE TABLE `event_maison_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ceremony_id` int NOT NULL,
	`edition_code` varchar(32) NOT NULL DEFAULT 'AQ–001',
	`seal_label` varchar(128) NOT NULL DEFAULT 'دار العقيق',
	`premiere_title` varchar(255) NOT NULL DEFAULT 'إصدار من دار العقيق',
	`premiere_phrase` text,
	`cover_url` varchar(1024),
	`launch_phase` enum('sealed','reveal','live','archive') NOT NULL DEFAULT 'sealed',
	`launch_note` varchar(255),
	`honor_title` varchar(255) NOT NULL DEFAULT 'صالة الشرف',
	`honor_message` text,
	`honor_program` text,
	`portrait_quote` text,
	`portrait_highlights` text,
	`portrait_video_url` varchar(1024),
	`curtain_title` varchar(255) NOT NULL DEFAULT 'لحظة كشف الستار',
	`curtain_subtitle` text,
	`curtain_state` enum('closed','opening','revealed') NOT NULL DEFAULT 'closed',
	`updated_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_maison_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `uk_event_maison_ceremony` UNIQUE(`ceremony_id`)
);
