import { BookOpen, Crown, ExternalLink, FolderArchive, Images, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { VisualEditable } from "@/components/VisualEditor";

const phaseLabels: Record<string, string> = { sealed: "ختم محفوظ", reveal: "إصدار مفتوح", live: "ليلة العقيق", archive: "سجل محفوظ" };

export default function MaisonVaultPage() {
  const { data: entries, isLoading } = trpc.ceremonies.maison.vault.useQuery(undefined, { refetchOnWindowFocus: false });
  if (isLoading) return <div className="flex min-h-screen items-center justify-center bg-[#06070a]"><div className="h-9 w-9 animate-spin rounded-full border-2 border-amber-300 border-t-transparent" /></div>;

  const hasEntries = (entries ?? []).length > 0;
  const newest = entries?.[0];
  return <main dir="rtl" className="min-h-screen bg-[#06070a] text-slate-100"><div className="pointer-events-none fixed inset-0" style={{ background: "radial-gradient(circle at 80% 4%, rgba(221,165,49,.17), transparent 24%), radial-gradient(circle at 11% 90%, rgba(139,92,246,.14), transparent 23%)" }} /><div className="relative mx-auto max-w-7xl px-5 py-12 md:py-20"><header className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-amber-300/20 bg-amber-300/[0.05] px-3 py-1.5 text-[11px] font-black text-amber-200"><FolderArchive size={14} />دار العقيق · الخزنة الرقمية</div><VisualEditable id="maison-vault-title" tag="text" label="عنوان خزنة مواسم العقيق" as="h1" defaultText="مواسم العقيق" className="mt-5 text-5xl font-black leading-tight text-amber-50 md:text-7xl" /><VisualEditable id="maison-vault-subtitle" tag="text" label="وصف خزنة مواسم العقيق" as="p" defaultText="إصدارات محفوظة، تجارب أُطلقت، ولحظات صنعت هوية العقيق." className="mt-5 max-w-2xl text-lg leading-9 text-slate-400" /></header>

    <section className="mt-10 grid gap-3 md:grid-cols-3" aria-label="ممر الذاكرة الموسمي"><a href="/news" className="group rounded-3xl border border-amber-300/20 bg-amber-300/[.045] p-5 transition hover:-translate-y-1 hover:border-amber-300/50"><BookOpen className="text-amber-300" size={20} /><div className="mt-5 text-xs font-black text-amber-300">الخبر الأسبوعي</div><h2 className="mt-1 text-lg font-black text-amber-50">نشرة العقيق</h2><p className="mt-2 text-xs leading-6 text-slate-400">ابدأ من أخبار الأسبوع ثم انتقل إلى الكتيبات الشهرية.</p></a><a href="/journal" className="group rounded-3xl border border-sky-300/20 bg-sky-300/[.04] p-5 transition hover:-translate-y-1 hover:border-sky-300/50"><FolderArchive className="text-sky-200" size={20} /><div className="mt-5 text-xs font-black text-sky-200">الأرشيف المفتوح</div><h2 className="mt-1 text-lg font-black text-amber-50">مكتبة الموسم</h2><p className="mt-2 text-xs leading-6 text-slate-400">اقرأ أعداد المجلة المستقلة بعيداً عن أدوات الإدارة.</p></a>{newest ? <a href={`/event/${newest.event.id}/memories`} className="group rounded-3xl border border-violet-300/20 bg-violet-300/[.04] p-5 transition hover:-translate-y-1 hover:border-violet-300/50"><Images className="text-violet-200" size={20} /><div className="mt-5 text-xs font-black text-violet-200">الذكرى الأخيرة</div><h2 className="mt-1 text-lg font-black text-amber-50">بوابة ذكريات الفعالية</h2><p className="mt-2 text-xs leading-6 text-slate-400">افتح مواد {newest.event.title} المعتمدة كما تُحفظ في الموسم.</p></a> : <div className="rounded-3xl border border-dashed border-slate-700 bg-white/[.02] p-5"><Images className="text-slate-600" size={20} /><h2 className="mt-5 text-lg font-black text-slate-300">بوابة الذكريات</h2><p className="mt-2 text-xs leading-6 text-slate-500">تظهر عند إطلاق أول فعالية وحفظ موادها.</p></div>}</section>

    <VisualEditable id="maison-vault-grid" tag="section" label="بطاقات خزنة مواسم العقيق" as="section" className="mt-12 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{hasEntries ? (entries ?? []).map(({ event, maison }) => <a key={event.id} href={`/event/${event.id}/premiere`} className="group relative min-h-[330px] overflow-hidden rounded-[2rem] border border-white/[0.09] bg-[#0d0f16] p-6 transition duration-300 hover:-translate-y-1 hover:border-amber-300/35"><div className="absolute inset-0 opacity-35 transition duration-500 group-hover:scale-105 group-hover:opacity-50" style={maison.coverUrl ? { backgroundImage: `url(${maison.coverUrl})`, backgroundSize: "cover", backgroundPosition: "center" } : { background: `radial-gradient(circle at 75% 15%, ${event.brandColor || "#dca631"}6a, transparent 27%), linear-gradient(145deg, #16110b, #06070a)` }} /><div className="absolute inset-0 bg-gradient-to-t from-[#07080d] via-[#07080d]/35 to-transparent" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between"><span className="rounded-full border border-white/10 bg-black/25 px-3 py-1.5 text-[10px] font-black text-amber-100">{maison.editionCode}</span><ExternalLink size={16} className="text-amber-200 opacity-0 transition group-hover:opacity-100" /></div><div><div className="inline-flex items-center gap-2 text-[10px] font-black text-slate-400"><span className="h-1.5 w-1.5 rounded-full" style={{ background: event.brandColor || "#dca631" }} />{phaseLabels[maison.launchPhase]}</div><h2 className="mt-3 text-2xl font-black leading-tight text-white">{event.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-7 text-slate-400">{maison.premierePhrase || event.subtitle || "إصدار من دار العقيق."}</p><div className="mt-5 inline-flex items-center gap-2 text-xs font-black text-amber-200"><Crown size={14} />{maison.sealLabel}</div></div></div></a>) : <div className="col-span-full rounded-3xl border border-dashed border-slate-700 bg-white/[0.02] p-12 text-center text-sm text-slate-500"><Sparkles className="mx-auto mb-3 text-amber-300" />ستظهر هنا إصدارات فعاليات العقيق بعد إنشائها.</div>}</VisualEditable>
  </div></main>;
}
