import { Activity, BarChart3, CheckCircle2, Clock3, Download, Loader2, PieChart, Radio, ShieldAlert, Users } from "lucide-react";
import * as XLSX from "xlsx";
import { trpc } from "../lib/trpc";
import { TICKET_TYPE_LABELS, PAYMENT_STATUS_LABELS } from "../../../shared/types";
import { VisualEditable } from "../components/VisualEditor";

function Breakdown({ title, icon: Icon, rows }: { title: string; icon: React.ElementType; rows: Array<{ label: string | null; count: number }> }) {
  const total = rows.reduce((sum, row) => sum + Number(row.count), 0);
  return <section className="card-dark rounded-2xl border p-5" style={{ borderColor: "oklch(25% 0.02 250)" }}><div className="mb-4 flex items-center gap-2 text-amber-200"><Icon size={17} /><h3 className="font-bold">{title}</h3></div>{rows.length ? <div className="space-y-3">{rows.map((row) => { const value = Number(row.count); const percent = total ? Math.round(value / total * 100) : 0; const label = row.label || "غير محدد"; return <div key={label} className="space-y-1"><div className="flex justify-between text-xs"><span className="text-slate-300">{label}</span><span className="text-amber-300">{value} · {percent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full" style={{ width: `${percent}%`, background: "var(--gold-gradient)" }} /></div></div>; })}</div> : <p className="text-sm text-slate-500">لا توجد بيانات كافية.</p>}</section>;
}

function EventReplay({ ceremonyId, total, attended }: { ceremonyId?: number; total: number; attended: number }) {
  const { data: logs = [] } = trpc.scan.logs.useQuery({ ceremonyId, limit: 100 }, { enabled: Boolean(ceremonyId) });
  const accepted = logs.filter((log) => log.result === "success").length; const exceptions = logs.filter((log) => log.result !== "success").length;
  const byGate = Object.entries(logs.reduce<Record<string, number>>((acc, log) => { const gate = log.gate || "استقبال عام"; acc[gate] = (acc[gate] || 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]);
  const topGate = byGate[0]; const rate = total ? Math.round(attended / total * 100) : 0;
  const decision = !logs.length ? "لم تبدأ عمليات المسح بعد؛ جهّز بوابة الاستقبال والفريق قبل فتح الدخول." : exceptions ? `راجع ${exceptions} حالة استثنائية قبل إغلاق الفعالية أو أرشفتها.` : rate >= 85 ? "الوصول مكتمل تقريباً؛ انتقل إلى المتأخرين وتوثيق ختام الفعالية." : "استمر في مراقبة البوابات؛ معدل الوصول يشير إلى أن الجزء الأساسي من الضيوف لم يصل بعد.";
  return <section className="rounded-3xl border border-amber-400/20 bg-[radial-gradient(circle_at_85%_0%,rgba(251,191,36,.12),transparent_35%),#10141e] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-amber-400/10 p-2 text-amber-300"><Radio size={18} /></div><div><div className="text-xs font-black text-amber-300">أرشيف الفعالية الحي</div><h3 className="mt-1 font-black text-amber-100">إعادة تشغيل يوم الفعالية</h3></div></div><div className="rounded-full bg-black/20 px-3 py-1 text-xs font-bold text-slate-400">آخر 100 عملية</div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={CheckCircle2} color="text-emerald-300" value={accepted} label="لحظات دخول ناجحة" /><Metric icon={ShieldAlert} color={exceptions ? "text-rose-300" : "text-slate-500"} value={exceptions} label="حالات استثنائية" /><Metric icon={Activity} color="text-sky-300" value={`${rate}%`} label="الحضور النهائي" /></div><div className="mt-4 grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border border-white/[.07] bg-black/20 p-4"><div className="flex items-center gap-2 text-xs font-black text-amber-100"><Clock3 size={15} />قرار التقرير التنفيذي</div><p className="mt-3 text-sm leading-7 text-slate-300">{decision}</p>{topGate && <div className="mt-4 rounded-xl bg-white/[.04] p-3 text-xs text-slate-400">أكثر نقطة نشاط: <span className="font-black text-amber-200">{topGate[0]}</span> · {topGate[1]} عملية مسح</div>}</div><div className="rounded-2xl border border-white/[.07] bg-black/20 p-4"><div className="text-xs font-black text-slate-500">اللحظات الأخيرة</div>{logs.length ? <div className="mt-3 space-y-2">{logs.slice(0, 5).map((log) => <div key={log.id} className="flex items-center justify-between gap-3 rounded-lg bg-white/[.025] px-3 py-2"><div><div className="text-xs font-bold text-slate-200">{log.gate || "استقبال عام"}</div><div className="mt-0.5 text-[10px] text-slate-500">{new Date(log.scannedAt).toLocaleTimeString("ar-SA", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</div></div><span className={`text-[11px] font-bold ${log.result === "success" ? "text-emerald-300" : "text-rose-300"}`}>{log.result === "success" ? "دخول ناجح" : "مراجعة"}</span></div>)}</div> : <div className="mt-3 text-sm text-slate-500">ستظهر هنا أولى لحظات استقبال الضيوف.</div>}</div></div></section>;
}

function Metric({ icon: Icon, color, value, label }: { icon: React.ElementType; color: string; value: string | number; label: string }) { return <div className="rounded-2xl bg-black/25 p-4"><Icon className={color} size={18} /><div className="mt-2 text-2xl font-black text-slate-100">{value}</div><div className="mt-1 text-[11px] text-slate-500">{label}</div></div>; }

export default function ReportsPage({ ceremonyId }: { ceremonyId?: number }) {
  const summary = trpc.reports.summary.useQuery(ceremonyId ? { ceremonyId } : undefined);
  const stats = trpc.attendees.stats.useQuery(ceremonyId ? { ceremonyId } : undefined);
  const ceremony = trpc.ceremonies.list.useQuery();
  const active = ceremony.data?.find((item) => item.id === ceremonyId) || ceremony.data?.find((item) => item.isActive);
  const exportReport = () => { if (!summary.data) return; const rows = [...summary.data.byTicket.map((row) => ({ الفئة: "نوع التذكرة", البيان: TICKET_TYPE_LABELS[row.label as keyof typeof TICKET_TYPE_LABELS] || row.label || "غير محدد", العدد: row.count })), ...summary.data.byPayment.map((row) => ({ الفئة: "حالة الدفع", البيان: PAYMENT_STATUS_LABELS[row.label as keyof typeof PAYMENT_STATUS_LABELS] || row.label || "غير محدد", العدد: row.count })), ...summary.data.bySection.map((row) => ({ الفئة: "القطاع", البيان: row.label || "غير محدد", العدد: row.count })), ...summary.data.byGate.map((row) => ({ الفئة: "البوابة", البيان: row.label || "غير محدد", العدد: row.count }))]; const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), "التقرير التنفيذي"); XLSX.writeFile(wb, `تقرير_الفعالية_${new Date().toISOString().slice(0, 10)}.xlsx`); };
  const total = stats.data?.total ?? 0; const attended = stats.data?.attended ?? 0;
  return <div className="space-y-5"><VisualEditable id="reports-header-section" tag="section" label="ترويسة التقارير" as="section" className="flex flex-wrap items-center justify-between gap-3"><div><VisualEditable id="reports-title" tag="text" label="عنوان التقارير" as="h2" defaultText="التقارير التنفيذية" className="text-xl font-black text-amber-100" /><VisualEditable id="reports-subtitle" tag="text" label="وصف التقارير" as="p" defaultText={`${active?.title || "الفعالية المحددة"} — قراءة سريعة لتوزيع الضيوف والتجهيزات التشغيلية.`} className="mt-1 text-sm text-slate-400" /></div><VisualEditable id="reports-export-cta" tag="button" label="زر تصدير التقرير" as="button" defaultText="تصدير التقرير" onAction={exportReport} className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold text-amber-950 disabled:opacity-50" style={{ background: "var(--gold-gradient)" }}>{(text) => <><Download size={16} /> {text}</>}</VisualEditable></VisualEditable><div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric icon={Users} color="text-amber-400" value={total} label="إجمالي الضيوف" /><Metric icon={PieChart} color="text-emerald-400" value={attended} label="تم تسجيل دخولهم" /><Metric icon={BarChart3} color="text-sky-400" value={stats.data?.paid ?? 0} label="التذاكر المدفوعة" /><Metric icon={Download} color="text-violet-300" value={`${total ? Math.round(attended / total * 100) : 0}%`} label="نسبة الحضور" /></div><EventReplay ceremonyId={ceremonyId} total={total} attended={attended} />{summary.isLoading ? <div className="card-dark rounded-2xl p-10 text-center text-slate-400"><Loader2 className="mx-auto animate-spin" /></div> : <div className="grid gap-4 lg:grid-cols-2"><Breakdown title="توزيع التذاكر" icon={Users} rows={summary.data?.byTicket || []} /><Breakdown title="حالة الدفع" icon={PieChart} rows={summary.data?.byPayment || []} /><Breakdown title="القطاعات" icon={BarChart3} rows={summary.data?.bySection || []} /><Breakdown title="البوابات" icon={BarChart3} rows={summary.data?.byGate || []} /></div>}</div>;
}
