export type SystemPortalCategory = "parents_students" | "staff_admin" | "public";

export interface SystemPortalItem {
  id: string;
  title: string;
  description: string;
  url: string;
  category: SystemPortalCategory;
  iconName: string;
  badge?: string;
  visible: boolean;
  order: number;
  openInNewTab?: boolean;
}

export const PORTAL_CATEGORY_LABELS: Record<SystemPortalCategory, string> = {
  parents_students: "خدمات أولياء الأمور والطلاب",
  staff_admin: "الأنظمة الإدارية والموظفين",
  public: "خدمات ومنصات عامة",
};

export type PortalIconCategory =
  | "all"
  | "education"
  | "services"
  | "finance"
  | "communication"
  | "tech"
  | "activities";

export const PORTAL_ICON_CATEGORY_LABELS: Record<
  PortalIconCategory,
  { label: string; emoji: string }
> = {
  all: { label: "الكل", emoji: "✨" },
  education: { label: "تعليم وأكاديميا", emoji: "🎓" },
  services: { label: "خدمات ومرافق", emoji: "🚌" },
  finance: { label: "مالية وإدارة", emoji: "💼" },
  communication: { label: "تواصل وإعلام", emoji: "📢" },
  tech: { label: "تقنية وأنظمة", emoji: "⚙️" },
  activities: { label: "أنشطة وتميز", emoji: "🏆" },
};

export interface PortalIconOption {
  id: string;
  label: string;
  icon: string;
  category: Exclude<PortalIconCategory, "all">;
  keywords: string[];
}

export const AVAILABLE_PORTAL_ICONS: readonly PortalIconOption[] = [
  // --- التعليم والأكاديميا (Education) ---
  {
    id: "file-text",
    label: "خطط ومستندات",
    icon: "FileText",
    category: "education",
    keywords: ["خطط", "مستند", "واجبات", "أسبوعي", "ملف", "pdf", "درس"],
  },
  {
    id: "graduation-cap",
    label: "قبعة تخرج / طلاب",
    icon: "GraduationCap",
    category: "education",
    keywords: ["تخرج", "طالب", "دراسة", "شهادة", "جامعة", "أكاديمي"],
  },
  {
    id: "book-open",
    label: "كتاب مفتوح / مناهج",
    icon: "BookOpen",
    category: "education",
    keywords: ["كتاب", "مناهج", "قراءة", "مقرر", "دراسة", "فهرس"],
  },
  {
    id: "book",
    label: "كتاب مدرسي",
    icon: "Book",
    category: "education",
    keywords: ["كتاب", "مقررات", "دفتر", "تعليم"],
  },
  {
    id: "library",
    label: "مكتبة ومراجع",
    icon: "Library",
    category: "education",
    keywords: ["مكتبة", "مراجع", "أبحاث", "كتب", "استعارة"],
  },
  {
    id: "file-check",
    label: "اختبارات ونتائج",
    icon: "FileCheck",
    category: "education",
    keywords: ["اختبار", "امتحان", "نتائج", "درجات", "شهادات", "تصحيح"],
  },
  {
    id: "pen-tool",
    label: "قلم وواجبات",
    icon: "PenTool",
    category: "education",
    keywords: ["قلم", "كتابة", "واجب", "إنشاء", "رسم", "تعبير"],
  },
  {
    id: "school",
    label: "مبنى مدرسي / حرم",
    icon: "School",
    category: "education",
    keywords: ["مدرسة", "مجمع", "مبنى", "حرم", "فصول"],
  },
  {
    id: "calculator",
    label: "آلة حاسبة ورياضيات",
    icon: "Calculator",
    category: "education",
    keywords: ["حاسبة", "رياضيات", "أرقام", "حساب", "معادلات"],
  },
  {
    id: "microscope",
    label: "مختبر وعلوم",
    icon: "Microscope",
    category: "education",
    keywords: ["مختبر", "علوم", "فيزياء", "كيمياء", "أحياء", "تجارب"],
  },
  {
    id: "languages",
    label: "لغات وترجمة",
    icon: "Languages",
    category: "education",
    keywords: ["لغات", "إنجليزي", "عربي", "ترجمة", "حوار"],
  },
  {
    id: "lightbulb",
    label: "أفكار وموهبة",
    icon: "Lightbulb",
    category: "education",
    keywords: ["فكرة", "موهبة", "ابتكار", "ذكاء", "إبداع"],
  },

  // --- الخدمات والمرافق (Services & Logistics) ---
  {
    id: "bus",
    label: "حافلة ونقل مدرسي",
    icon: "Bus",
    category: "services",
    keywords: ["باص", "حافلة", "نقل", "مواصلات", "مسار", "سائق"],
  },
  {
    id: "ticket",
    label: "تذاكر وصيانة",
    icon: "Ticket",
    category: "services",
    keywords: ["تذكرة", "صيانة", "دعم", "طلب", "بلاغ", "عطل"],
  },
  {
    id: "utensils",
    label: "مقصف وتغذية",
    icon: "Utensils",
    category: "services",
    keywords: ["مقصف", "طعام", "وجبات", "تغذية", "مطعم", "إفطار"],
  },
  {
    id: "heart-pulse",
    label: "عيادة وصحة مدرسية",
    icon: "HeartPulse",
    category: "services",
    keywords: ["صحة", "عيادة", "إسعاف", "طبيب", "تمريض", "علاج"],
  },
  {
    id: "wrench",
    label: "صيانة وتشغيل",
    icon: "Wrench",
    category: "services",
    keywords: ["صيانة", "تشغيل", "فني", "إصلاح", "أجهزة"],
  },
  {
    id: "clock",
    label: "مواعيد ودوام",
    icon: "Clock",
    category: "services",
    keywords: ["وقت", "ساعة", "دوام", "حضور", "موعد", "جدول"],
  },
  {
    id: "calendar",
    label: "تقويم وفعاليات",
    icon: "Calendar",
    category: "services",
    keywords: ["تقويم", "تاريخ", "فعاليات", "أجندة", "مناسبات", "فصل"],
  },
  {
    id: "map-pin",
    label: "موقع وملاحة",
    icon: "MapPin",
    category: "services",
    keywords: ["موقع", "خريطة", "فرع", "عنوان", "لوكيشن", "طريق"],
  },
  {
    id: "building",
    label: "مرافق وقاعات",
    icon: "Building",
    category: "services",
    keywords: ["مبنى", "قاعة", "مسرح", "مرافق", "مجمع"],
  },
  {
    id: "key",
    label: "أذونات ودخول",
    icon: "Key",
    category: "services",
    keywords: ["مفتاح", "دخول", "تصريح", "إذن", "أمان"],
  },
  {
    id: "coffee",
    label: "ضيافة واستراحة",
    icon: "Coffee",
    category: "services",
    keywords: ["قهوة", "استراحة", "ضيافة", "مجلس"],
  },

  // --- المالية والإدارة (Finance & Admin) ---
  {
    id: "briefcase",
    label: "حقيبة عمل / ERP",
    icon: "Briefcase",
    category: "finance",
    keywords: ["إدارة", "عمل", "erp", "odoo", "موظفين", "أعمال", "شركة"],
  },
  {
    id: "shield",
    label: "إدارة وأمان",
    icon: "Shield",
    category: "finance",
    keywords: ["أمان", "حماية", "أدمن", "صلاحيات", "إشراف", "أمن"],
  },
  {
    id: "credit-card",
    label: "دفع إلكتروني وبطاقات",
    icon: "CreditCard",
    category: "finance",
    keywords: ["بطاقة", "دفع", "فيزا", "مدى", "سداد", "أقساط", "رسوم"],
  },
  {
    id: "wallet",
    label: "محفظة ورسوم",
    icon: "Wallet",
    category: "finance",
    keywords: ["محفظة", "رسوم", "أقساط", "مالية", "رصيد"],
  },
  {
    id: "receipt",
    label: "فاتورة وسند قبض",
    icon: "Receipt",
    category: "finance",
    keywords: ["فاتورة", "سند", "إيصال", "ضريبة", "محاسبة"],
  },
  {
    id: "dollar-sign",
    label: "شؤون مالية",
    icon: "DollarSign",
    category: "finance",
    keywords: ["مالية", "نقود", "سعر", "ميزانية", "حسابات"],
  },
  {
    id: "circle-dollar-sign",
    label: "سداد ورسوم",
    icon: "CircleDollarSign",
    category: "finance",
    keywords: ["سداد", "رسوم", "دفع", "أقساط", "تحصيل"],
  },
  {
    id: "banknote",
    label: "نقد ومدفوعات",
    icon: "Banknote",
    category: "finance",
    keywords: ["كاش", "نقد", "مدفوعات", "أموال", "خزينة"],
  },
  {
    id: "scale",
    label: "لوائح وقوانين",
    icon: "Scale",
    category: "finance",
    keywords: ["قانون", "لائحة", "عدالة", "شؤون", "نظام", "ميزان"],
  },
  {
    id: "folder",
    label: "سجلات وملفات إدارية",
    icon: "Folder",
    category: "finance",
    keywords: ["مجلد", "سجلات", "أرشيف", "وثائق", "إدارة"],
  },
  {
    id: "file-spreadsheet",
    label: "جداول وإكسل",
    icon: "FileSpreadsheet",
    category: "finance",
    keywords: ["إكسل", "جدول", "بيانات", "إحصاء", "أرقام"],
  },

  // --- التواصل والإعلام (Communication & Media) ---
  {
    id: "mail",
    label: "بريد إلكتروني رسمي",
    icon: "Mail",
    category: "communication",
    keywords: ["بريد", "ايميل", "إيميل", "رسالة", "webmail", "مراسلة"],
  },
  {
    id: "video",
    label: "اجتماعات مرئية وبث",
    icon: "Video",
    category: "communication",
    keywords: ["فيديو", "اجتماع", "بث", "زووم", "تيمز", "لقاء", "مرئي"],
  },
  {
    id: "message-square",
    label: "محادثة ودعم فوري",
    icon: "MessageSquare",
    category: "communication",
    keywords: ["شات", "محادثة", "رسائل", "واتساب", "دعم", "تواصل"],
  },
  {
    id: "phone",
    label: "هاتف واتصال",
    icon: "Phone",
    category: "communication",
    keywords: ["هاتف", "تليفون", "جوال", "اتصال", "سنترال", "رقم"],
  },
  {
    id: "bell",
    label: "تنبيهات وإعلانات",
    icon: "Bell",
    category: "communication",
    keywords: ["جرس", "تنبيه", "إشعار", "إعلان", "عاجل", "خبر"],
  },
  {
    id: "send",
    label: "مراسلات فورية",
    icon: "Send",
    category: "communication",
    keywords: ["إرسال", "برقية", "تيليجرام", "رسالة", "مباشر"],
  },
  {
    id: "share-2",
    label: "مشاركة وتواصل",
    icon: "Share2",
    category: "communication",
    keywords: ["مشاركة", "نشر", "تواصل", "سوشيال", "رابط"],
  },
  {
    id: "headphones",
    label: "دعم صوتي ومركز اتصال",
    icon: "Headphones",
    category: "communication",
    keywords: ["سماعة", "دعم", "صوت", "مركز اتصال", "كول سنتر"],
  },
  {
    id: "radio",
    label: "إذاعة وبودكاست",
    icon: "Radio",
    category: "communication",
    keywords: ["راديو", "إذاعة", "بودكاست", "صوتيات", "أثير"],
  },
  {
    id: "newspaper",
    label: "صحيفة وأخبار المدرسة",
    icon: "Newspaper",
    category: "communication",
    keywords: ["صحيفة", "جريدة", "أخبار", "نشرة", "مجلة"],
  },
  {
    id: "inbox",
    label: "صندوق الوارد والطلبات",
    icon: "Inbox",
    category: "communication",
    keywords: ["وارد", "طلبات", "رسائل", "بريد", "صندوق"],
  },
  {
    id: "help-circle",
    label: "استفسارات وأسئلة شائعة",
    icon: "HelpCircle",
    category: "communication",
    keywords: ["مساعدة", "سؤال", "استفسار", "دليل", "تعليمات"],
  },

  // --- التقنية والأنظمة (Tech & Systems) ---
  {
    id: "smartphone",
    label: "هاتف / تطبيق ذكي",
    icon: "Smartphone",
    category: "tech",
    keywords: ["موبايل", "تطبيق", "جوال", "ios", "android", "آب"],
  },
  {
    id: "cloud",
    label: "سحابة رقمية وتخزين",
    icon: "Cloud",
    category: "tech",
    keywords: ["سحابي", "كلاود", "تخزين", "nextcloud", "drive", "ملفات"],
  },
  {
    id: "database",
    label: "قواعد بيانات وسجلات",
    icon: "Database",
    category: "tech",
    keywords: ["قاعدة", "بيانات", "سجلات", "داتا", "تخزين"],
  },
  {
    id: "server",
    label: "خوادم وأنظمة مركزية",
    icon: "Server",
    category: "tech",
    keywords: ["سيرفر", "خادم", "استضافة", "شبكة"],
  },
  {
    id: "qr-code",
    label: "رمز استجابة QR",
    icon: "QrCode",
    category: "tech",
    keywords: ["باركود", "qr", "رمز", "مسح", "كود"],
  },
  {
    id: "wifi",
    label: "شبكة وإنترنت",
    icon: "Wifi",
    category: "tech",
    keywords: ["واي فاي", "نت", "إنترنت", "اتصال", "شبكة"],
  },
  {
    id: "bar-chart",
    label: "تقارير وإحصائيات",
    icon: "BarChart3",
    category: "tech",
    keywords: ["إحصاء", "تقرير", "بيانات", "مخطط", "أرقام", "رسم بياني"],
  },
  {
    id: "pie-chart",
    label: "مؤشرات أداء ونسب",
    icon: "PieChart",
    category: "tech",
    keywords: ["نسبة", "مؤشر", "رادار", "أداء", "تحليل"],
  },
  {
    id: "users",
    label: "مستخدمين ومجتمع",
    icon: "Users",
    category: "tech",
    keywords: ["مستخدمين", "أولياء أمور", "معلمين", "مجتمع", "أعضاء"],
  },
  {
    id: "user-check",
    label: "حضور وغياب وتفقد",
    icon: "UserCheck",
    category: "tech",
    keywords: ["حضور", "غياب", "تفقد", "انضباط", "تسجيل"],
  },
  {
    id: "settings",
    label: "إعدادات النظام",
    icon: "Settings",
    category: "tech",
    keywords: ["إعدادات", "تخصيص", "ضبط", "خيارات", "تحكم"],
  },
  {
    id: "lock",
    label: "أمان وكلمات مرور",
    icon: "Lock",
    category: "tech",
    keywords: ["قفل", "أمان", "باسورد", "حماية", "تسجيل دخول"],
  },
  {
    id: "shield-check",
    label: "تحقق واعتماد أمني",
    icon: "ShieldCheck",
    category: "tech",
    keywords: ["تحقق", "توثيق", "اعتماد", "موثوق", "حماية"],
  },
  {
    id: "cpu",
    label: "ذكاء اصطناعي ومعالجة",
    icon: "Cpu",
    category: "tech",
    keywords: ["ذكاء اصطناعي", "معالج", "حوسبة", "تقنية", "روبوت"],
  },
  {
    id: "laptop",
    label: "بوابة ويب وحاسوب",
    icon: "Laptop",
    category: "tech",
    keywords: ["لابتوب", "كمبيوتر", "منصة", "ويب", "موقع"],
  },
  {
    id: "globe",
    label: "موقع ويب عام",
    icon: "Globe",
    category: "tech",
    keywords: ["موقع", "إنترنت", "عالمي", "دولي", "ويب"],
  },
  {
    id: "link",
    label: "رابط خارجي",
    icon: "ExternalLink",
    category: "tech",
    keywords: ["رابط", "خارجي", "لينك", "عنوان", "توجيه"],
  },
  {
    id: "layers",
    label: "منظومات متكاملة",
    icon: "Layers",
    category: "tech",
    keywords: ["طبقات", "منظومة", "تكامل", "بنية"],
  },
  {
    id: "download",
    label: "تحميل وتنزيل ملفات",
    icon: "Download",
    category: "tech",
    keywords: ["تحميل", "تنزيل", "داونلود", "ملف"],
  },
  {
    id: "upload",
    label: "رفع مستندات ونماذج",
    icon: "Upload",
    category: "tech",
    keywords: ["رفع", "إرفاق", "ملفات", "مستندات"],
  },
  {
    id: "printer",
    label: "طباعة تقارير وكشوفات",
    icon: "Printer",
    category: "tech",
    keywords: ["طباعة", "طابعة", "كشف", "ورق", "تقرير"],
  },
  {
    id: "search",
    label: "بحث واستعلام",
    icon: "Search",
    category: "tech",
    keywords: ["بحث", "استعلام", "عدسة", "تدقيق"],
  },

  // --- الأنشطة والتميز (Activities & Excellence) ---
  {
    id: "trophy",
    label: "كؤوس وبطولات",
    icon: "Trophy",
    category: "activities",
    keywords: ["كأس", "بطولة", "فوز", "أول", "مسابقة", "دوري"],
  },
  {
    id: "award",
    label: "جوائز وتكريم",
    icon: "Award",
    category: "activities",
    keywords: ["جائزة", "تكريم", "شهادة", "شكر", "تقدير"],
  },
  {
    id: "medal",
    label: "ميداليات شرف",
    icon: "Medal",
    category: "activities",
    keywords: ["ميدالية", "مركز", "تكريم", "شرف", "ذهبية"],
  },
  {
    id: "star",
    label: "لوحة الشرف والنجوم",
    icon: "Star",
    category: "activities",
    keywords: ["نجم", "نجوم", "شرف", "متميز", "متفوق", "تقييم"],
  },
  {
    id: "sparkles",
    label: "ابتكار وموهبة خاصة",
    icon: "Sparkles",
    category: "activities",
    keywords: ["إبداع", "بريق", "تميز", "ابتكار", "موهبة"],
  },
  {
    id: "compass",
    label: "إرشاد وتوجيه طلابي",
    icon: "Compass",
    category: "activities",
    keywords: ["إرشاد", "توجيه", "بوصلة", "مسار", "مستقبل"],
  },
  {
    id: "flag",
    label: "فعاليات ومناسبات وطنية",
    icon: "Flag",
    category: "activities",
    keywords: ["علم", "راية", "وطني", "يوم وطني", "تأسيس", "مناسبة"],
  },
  {
    id: "activity",
    label: "نشاط رياضي وحركي",
    icon: "Activity",
    category: "activities",
    keywords: ["رياضة", "نشاط", "حركة", "لياقة", "نبض"],
  },
  {
    id: "dumbbell",
    label: "صالة رياضية وتدريب",
    icon: "Dumbbell",
    category: "activities",
    keywords: ["جم", "تدريب", "أثقال", "صالة", "لياقة"],
  },
  {
    id: "music",
    label: "مواهب وأناشيد",
    icon: "Music",
    category: "activities",
    keywords: ["موسيقى", "نشيد", "موهبة", "فن", "إلقاء"],
  },
  {
    id: "camera",
    label: "تصوير وتغطيات إعلامية",
    icon: "Camera",
    category: "activities",
    keywords: ["كاميرا", "تصوير", "تغطية", "إعلام", "فوتوغرافي"],
  },
  {
    id: "image",
    label: "معرض وألبوم صور",
    icon: "Image",
    category: "activities",
    keywords: ["صور", "ألبوم", "معرض", "لقطات"],
  },
  {
    id: "heart",
    label: "تطوع ورعاية إنسانية",
    icon: "Heart",
    category: "activities",
    keywords: ["تطوع", "خيري", "إنساني", "رعاية", "عطاء", "حب"],
  },
  {
    id: "gift",
    label: "مكافآت وهدايا تشجيعية",
    icon: "Gift",
    category: "activities",
    keywords: ["هدية", "مكافأة", "حافز", "تشجيع", "مسابقة"],
  },
] as const;

export const DEFAULT_SYSTEM_PORTALS: SystemPortalItem[] = [
  {
    id: "portal-daily-plans",
    title: "الخطط الدراسية الأسبوعية",
    description: "متابعة الواجبات اليومية وجدول الحصص الأسبوعي للطلاب",
    url: "https://portal.aqeeq.app/pages/daily_plans/parent_lookup.php",
    category: "parents_students",
    iconName: "file-text",
    badge: "أولياء الأمور",
    visible: true,
    order: 1,
    openInNewTab: true,
  },
  {
    id: "portal-parent-app",
    title: "تحميل تطبيق أولياء الأمور",
    description: "تطبيق العقيق الذكي لمتابعة الدرجات والغياب والتواصل المباشر",
    url: "https://qr-codes.io/LQMip0",
    category: "parents_students",
    iconName: "smartphone",
    badge: "iOS & Android",
    visible: true,
    order: 2,
    openInNewTab: true,
  },
  {
    id: "portal-odoo-erp",
    title: "نظام Odoo الإداري",
    description: "المنظومة الإدارية والمالية وشؤون الموظفين والعمليات المدرسية",
    url: "https://live.aqeeq.edu.sa",
    category: "staff_admin",
    iconName: "briefcase",
    badge: "ERP",
    visible: true,
    order: 3,
    openInNewTab: true,
  },
  {
    id: "portal-official-email",
    title: "البريد الإلكتروني الرسمي",
    description: "منصة المراسلات والبريد الرسمي لمنسوبي مدارس العقيق",
    url: "https://email.aqeeqholding.com",
    category: "staff_admin",
    iconName: "mail",
    badge: "Webmail",
    visible: true,
    order: 4,
    openInNewTab: true,
  },
  {
    id: "portal-cloud-storage",
    title: "سحابة العقيق الرقمية",
    description: "التخزين السحابي الآمن ومشاركة المجلدات والملفات التعليمية",
    url: "https://next.aqeeq.app",
    category: "staff_admin",
    iconName: "cloud",
    badge: "NextCloud",
    visible: true,
    order: 5,
    openInNewTab: true,
  },
  {
    id: "portal-tickets-maintenance",
    title: "بوابة التذاكر والصيانة",
    description: "الدعم التقني والفني وطلبات الصيانة والمتابعة الفورية",
    url: "https://portal.aqeeq.app",
    category: "staff_admin",
    iconName: "ticket",
    badge: "IT Support",
    visible: true,
    order: 6,
    openInNewTab: true,
  },
  {
    id: "portal-live-meetings",
    title: "اجتماعات العقيق المرئية",
    description: "قاعات البث المرئي المباشر واللقاءات التفاعلية عن بعد",
    url: "https://aqeeq.live",
    category: "staff_admin",
    iconName: "video",
    badge: "Live Meet",
    visible: true,
    order: 7,
    openInNewTab: true,
  },
  {
    id: "portal-admin-dashboard",
    title: "لوحة الإدارة والتحكم",
    description: "بوابة دخول المشرفين لإدارة محتوى منصة استوديو العقيق",
    url: "/login",
    category: "staff_admin",
    iconName: "shield",
    badge: "Admin",
    visible: true,
    order: 8,
    openInNewTab: false,
  },
];
