import { trpc } from "@/lib/trpc";
import { BellRing, CalendarDays, Check, Loader2, Users, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type DrawerTab = "events" | "guests" | "notifications";

export default function EditorOperationsDrawer({ open, onClose, onManage }: { open: boolean; onClose: () => void; onManage: () => void }) {
  const [tab, setTab] = useState<DrawerTab>("events");
  const { data: events = [] } = trpc.ceremonies.list.useQuery(undefined, { enabled: open, refetchOnWindowFocus: false });
  const [eventId, setEventId] = useState<number | undefined>();
  const activeEventId = eventId ?? events.find((item) => item.isActive)?.id ?? events[0]?.id;
  const { data: stats } = trpc.attendees.stats.useQuery(activeEventId ? { ceremonyId: activeEventId } : undefined, { enabled: open, refetchInterval: 10000 });
  const { data: recentGuests } = trpc.attendees.list.useQuery(activeEventId ? { ceremonyId: activeEventId, limit: 6 } : undefined, { enabled: Boolean(open && activeEventId), refetchOnWindowFocus: false });
  const { data: recentNotifications = [] } = trpc.notifications.list.useQuery(activeEventId ? { ceremonyId: activeEventId, limit: 6 } : undefined, { enabled: Boolean(open && activeEventId), refetchOnWindowFocus: false });
  const utils = trpc.useUtils();
  const activate = trpc.ceremonies.activate.useMutation({ onSuccess: () => { toast.success("تم جعل الفعالية نشطة"); void utils.ceremonies.invalidate(); } });
  const guest = trpc.attendees.create.useMutation({ onSuccess: () => { toast.success("تمت إضافة الضيف"); void utils.attendees.invalidate(); void utils.attendees.stats.invalidate(); } });
  const notification = trpc.notifications.create.useMutation({ onSuccess: () => { toast.success("تم حفظ الإشعار كمسودة"); void utils.notifications.invalidate(); } });
  const updateGuest = trpc.attendees.update.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة الضيف"); void utils.attendees.invalidate(); } });
  const publishNotification = trpc.notifications.publish.useMutation({ onSuccess: () => { toast.success("تم نشر الإشعار"); void utils.notifications.invalidate(); } });
  const [guestForm, setGuestForm] = useState({ fullName: "", idNumber: "", ticketType: "guest" as "student" | "guardian" | "guest" | "vip", paymentStatus: "unpaid" as "paid" | "unpaid" | "exempt" });
  const [notice, setNotice] = useState({ title: "", message: "" });
  const total = Number(stats?.total ?? 0);
  const attended = Number(stats?.attended ?? 0);

  if (!open) return null;
  const tabs: Array<{ id: DrawerTab; label: string }> = [{ id: "events", label: "فعاليات" }, { id: "guests", label: "ضيف سريع" }, { id: "notifications", label: "إشعار" }];
  return <aside data-aq-editor-panel="operations" className="fixed inset-x-3 bottom-3 z-[340] flex max-h-[78svh] flex-col overflow-hidden rounded-3xl border border-sky-400/30 bg-[#101521]/95 shadow-2xl backdrop-blur-xl md:inset-y-0 md:left-0 md:right-auto md:max-h-none md:w-[min(430px,100vw)] md:rounded-none md:border-y-0 md:border-l-0 md:border-r" dir="rtl">
    <header className="flex items-start justify-between border-b border-white/[0.08] p-4"><div><div className="text-[11px] font-bold text-sky-300">تشغيل من داخل المحرر</div><h2 className="mt-1 text-base font-black text-slate-50">لوحة العمل السريعة</h2><p className="mt-1 text-[11px] text-slate-500">البيانات حقيقية وتُحفظ في المنصة فوراً.</p></div><button onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-white/[0.07] hover:text-white"><X size={17} /></button></header>
    <div className="flex gap-1 border-b border-white/[0.08] p-2">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`flex-1 rounded-xl px-2 py-2 text-[11px] font-black transition ${tab === item.id ? "bg-sky-400 text-sky-950" : "text-slate-400 hover:bg-white/[0.05]"}`}>{item.label}</button>)}</div>
    <div className="flex-1 overflow-y-auto p-4">
      <div className="mb-4 rounded-2xl border border-white/[0.07] bg-black/20 p-3"><label className="text-[11px] font-bold text-slate-400">الفعالية الحالية<select value={activeEventId ?? ""} onChange={(event) => setEventId(Number(event.target.value))} className="mt-1.5 w-full rounded-xl border border-slate-700 bg-[#101521] px-3 py-2 text-xs text-slate-100 outline-none focus:border-sky-400"><option value="">اختر فعالية</option>{events.map((event) => <option key={event.id} value={event.id}>{event.title}</option>)}</select></label><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/[0.04] p-2"><div className="text-lg font-black text-slate-100">{total}</div><div className="text-[10px] text-slate-500">الضيوف</div></div><div className="rounded-xl bg-white/[0.04] p-2"><div className="text-lg font-black text-emerald-300">{attended}</div><div className="text-[10px] text-slate-500">حضروا</div></div></div></div>
      {tab === "events" ? <div className="space-y-2">{events.length ? events.map((event) => <div key={event.id} className={`rounded-2xl border p-3 ${event.id === activeEventId ? "border-sky-400/45 bg-sky-400/[0.07]" : "border-white/[0.08] bg-black/20"}`}><div className="flex items-start justify-between gap-3"><button onClick={() => setEventId(event.id)} className="min-w-0 text-right"><div className="truncate text-sm font-black text-slate-100">{event.title}</div><div className="mt-1 flex items-center gap-1 text-[11px] text-slate-500"><CalendarDays size={12} />{event.ceremonyDate || "الموعد غير محدد"}</div></button>{event.isActive ? <span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-black text-emerald-300">نشطة</span> : <button onClick={() => activate.mutate({ id: event.id })} disabled={activate.isPending} className="rounded-lg border border-sky-400/35 px-2 py-1 text-[10px] font-bold text-sky-200">تفعيل</button>}</div></div>) : <EmptyState text="أنشئ فعالية أولاً لتظهر هنا." onManage={onManage} />}</div> : null}
      {tab === "guests" ? <div className="space-y-5"><form onSubmit={(event) => { event.preventDefault(); if (!activeEventId) return toast.error("اختر فعالية أولاً"); guest.mutate({ ...guestForm, ceremonyId: activeEventId }); setGuestForm((current) => ({ ...current, fullName: "", idNumber: "" })); }} className="space-y-3"><Field label="اسم الضيف" value={guestForm.fullName} onChange={(fullName) => setGuestForm((current) => ({ ...current, fullName }))} /><Field label="رقم الهوية" value={guestForm.idNumber} onChange={(idNumber) => setGuestForm((current) => ({ ...current, idNumber }))} /><div className="grid grid-cols-2 gap-3"><SelectField label="نوع التذكرة" value={guestForm.ticketType} options={[['guest','ضيف'],['vip','VIP'],['guardian','ولي أمر'],['student','طالب']]} onChange={(ticketType) => setGuestForm((current) => ({ ...current, ticketType: ticketType as typeof current.ticketType }))} /><SelectField label="الدفع" value={guestForm.paymentStatus} options={[['unpaid','غير مدفوع'],['paid','مدفوع'],['exempt','معفى']]} onChange={(paymentStatus) => setGuestForm((current) => ({ ...current, paymentStatus: paymentStatus as typeof current.paymentStatus }))} /></div><button disabled={guest.isPending} className="flex w-full items-center justify-center gap-2 rounded-xl bg-sky-400 px-3 py-3 text-xs font-black text-sky-950 disabled:opacity-50">{guest.isPending ? <Loader2 size={15} className="animate-spin" /> : <Users size={15} />}إضافة الضيف</button></form><div className="border-t border-white/[0.08] pt-4"><div className="mb-2 text-[11px] font-black text-sky-200">آخر الضيوف</div>{recentGuests?.items?.length ? <div className="space-y-2">{recentGuests.items.map((item) => <div key={item.id} className="flex items-center justify-between gap-2 rounded-xl bg-black/20 p-2.5"><div className="min-w-0"><div className="truncate text-xs font-bold text-slate-100">{item.fullName}</div><div className="mt-1 text-[10px] text-slate-500">{item.paymentStatus === "paid" ? "مدفوع" : "غير مدفوع"} · {item.attended ? "حضر" : "لم يحضر"}</div></div>{item.paymentStatus !== "paid" ? <button onClick={() => updateGuest.mutate({ id: item.id, paymentStatus: "paid" })} disabled={updateGuest.isPending} className="rounded-lg border border-emerald-400/35 px-2 py-1 text-[10px] font-bold text-emerald-300">تحصيل</button> : <Check size={15} className="text-emerald-300" />}</div>)}</div> : <p className="text-xs text-slate-500">لا يوجد ضيوف بعد.</p>}</div></div> : null}
      {tab === "notifications" ? <div className="space-y-5"><form onSubmit={(event) => { event.preventDefault(); if (!activeEventId) return toast.error("اختر فعالية أولاً"); notification.mutate({ ceremonyId: activeEventId, title: notice.title, message: notice.message, audience: "all", channel: "in_app" }); setNotice({ title: "", message: "" }); }} className="space-y-3"><Field label="عنوان الإشعار" value={notice.title} onChange={(title) => setNotice((current) => ({ ...current, title }))} /><label className="block text-xs font-bold text-slate-300">الرسالة<textarea value={notice.message} onChange={(event) => setNotice((current) => ({ ...current, message: event.target.value }))} className="mt-1.5 min-h-28 w-full rounded-xl border border-slate-700 bg-black/20 p-3 text-xs text-white outline-none focus:border-sky-400" /></label><button disabled={notification.isPending} className="flex w-full items-center justify-center gap-2 rounded-xl bg-sky-400 px-3 py-3 text-xs font-black text-sky-950 disabled:opacity-50">{notification.isPending ? <Loader2 size={15} className="animate-spin" /> : <BellRing size={15} />}حفظ إشعار كمسودة</button></form><div className="border-t border-white/[0.08] pt-4"><div className="mb-2 text-[11px] font-black text-sky-200">آخر الإشعارات</div>{recentNotifications.length ? <div className="space-y-2">{recentNotifications.map((item) => <div key={item.id} className="rounded-xl bg-black/20 p-2.5"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="truncate text-xs font-bold text-slate-100">{item.title}</div><div className="mt-1 line-clamp-1 text-[10px] text-slate-500">{item.message}</div></div>{item.status === "draft" ? <button onClick={() => publishNotification.mutate({ id: item.id })} disabled={publishNotification.isPending} className="rounded-lg border border-amber-400/35 px-2 py-1 text-[10px] font-bold text-amber-200">نشر</button> : <span className="text-[10px] font-bold text-emerald-300">منشور</span>}</div></div>)}</div> : <p className="text-xs text-slate-500">لا توجد إشعارات بعد.</p>}</div></div> : null}
    </div>
  </aside>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-xs font-bold text-slate-300">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-700 bg-black/20 px-3 py-2.5 text-xs text-white outline-none focus:border-sky-400" /></label>; }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: Array<[string, string]>; onChange: (value: string) => void }) { return <label className="text-[11px] font-bold text-slate-400">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-700 bg-[#101521] px-2 py-2 text-xs text-white outline-none focus:border-sky-400">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function EmptyState({ text, onManage }: { text: string; onManage: () => void }) { return <div className="rounded-2xl border border-dashed border-slate-700 p-5 text-center"><p className="text-xs text-slate-500">{text}</p><button onClick={onManage} className="mt-3 text-xs font-bold text-sky-300">فتح إدارة البيانات</button></div>; }
