import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleDot, ClipboardList, Loader2, Plus, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function EventReadinessBoard({ ceremonyId, brandColor, canManage }: { ceremonyId: number; brandColor: string; canManage: boolean }) {
  const utils = trpc.useUtils(); const { data: tasks = [], isLoading } = trpc.eventTasks.list.useQuery({ ceremonyId });
  const [title, setTitle] = useState(""); const [owner, setOwner] = useState("");
  const create = trpc.eventTasks.create.useMutation({ onSuccess: () => { setTitle(""); setOwner(""); void utils.eventTasks.list.invalidate({ ceremonyId }); toast.success("تمت إضافة مهمة الاستعداد"); }, onError: (error) => toast.error(error.message) });
  const update = trpc.eventTasks.update.useMutation({ onSuccess: () => void utils.eventTasks.list.invalidate({ ceremonyId }), onError: (error) => toast.error(error.message) });
  const done = tasks.filter((task) => task.status === "done").length; const readiness = tasks.length ? Math.round(done / tasks.length * 100) : 0;
  return <section className="rounded-3xl border border-white/[.08] bg-black/20 p-5" dir="rtl"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl p-2" style={{ color: brandColor, background: `${brandColor}18` }}><ClipboardList size={19} /></div><div><div className="text-xs font-black" style={{ color: brandColor }}>مركز الاستعداد</div><h3 className="mt-1 font-black text-amber-100">مهام فريق الفعالية</h3></div></div><div className="text-left"><div className="text-xl font-black text-amber-100">{readiness}%</div><div className="text-[10px] text-slate-500">مكتمل</div></div></div>{canManage && <div className="mt-5 grid gap-2 sm:grid-cols-[1fr_170px_auto]"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="مثال: اختبار بوابة الاستقبال" className="rounded-xl border border-slate-700 bg-black/20 px-3 py-2.5 text-sm text-white outline-none focus:border-amber-400" /><input value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="مسؤول المهمة" className="rounded-xl border border-slate-700 bg-black/20 px-3 py-2.5 text-sm text-white outline-none focus:border-amber-400" /><button disabled={!title.trim() || create.isPending} onClick={() => create.mutate({ ceremonyId, title: title.trim(), ownerLabel: owner.trim() || undefined })} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black text-slate-950 disabled:opacity-40" style={{ background: brandColor }}><Plus size={16} />إضافة</button></div>}<div className="mt-4 space-y-2">{isLoading ? <Loader2 className="mx-auto animate-spin text-amber-300" size={20} /> : tasks.length ? tasks.map((task) => <div key={task.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 bg-white/[.025] px-3 py-3"><button disabled={!canManage || update.isPending} onClick={() => update.mutate({ id: task.id, status: task.status === "done" ? "todo" : "done" })} className="shrink-0 disabled:cursor-default">{task.status === "done" ? <CheckCircle2 className="text-emerald-300" size={19} /> : <CircleDot className="text-amber-300" size={19} />}</button><div className="min-w-0 flex-1"><div className={`text-sm font-bold ${task.status === "done" ? "text-slate-500 line-through" : "text-slate-200"}`}>{task.title}</div>{task.ownerLabel && <div className="mt-1 flex items-center gap-1 text-[11px] text-slate-500"><UserRound size={12} />{task.ownerLabel}</div>}</div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${task.status === "done" ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-200"}`}>{task.status === "done" ? "مكتملة" : "مفتوحة"}</span></div>) : <div className="rounded-xl border border-dashed border-slate-700 px-4 py-5 text-center text-xs leading-6 text-slate-500">أضف مهام البوابات والاستقبال والدعوات كي يعرف كل شخص ما عليه قبل البداية.</div>}</div></section>;
}
