import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, ArrowLeft, CheckCircle2, Clock3, DoorOpen, Radio, ScanLine, ShieldAlert, Users } from "lucide-react";

function gates(value?: string | null) {
  return String(value || "").split(/[,،\n]/).map((item) => item.trim()).filter(Boolean);
}

export default function EventDayCommandCenter({ ceremonyId, gates: gateConfig, brandColor, onOpenScanner, onOpenGuests }: { ceremonyId: number; gates?: string | null; brandColor: string; onOpenScanner: () => void; onOpenGuests: () => void }) {
  const { data: stats } = trpc.attendees.stats.useQuery({ ceremonyId }, { refetchInterval: 10000 });
  const { data: logs = [] } = trpc.scan.logs.useQuery({ ceremonyId, limit: 100 }, { refetchInterval: 10000 });
  const total = stats?.total ?? 0; const attended = stats?.attended ?? 0; const rate = total ? Math.round((attended / total) * 100) : 0;
  const success = logs.filter((log) => log.result === "success").length; const attention = logs.filter((log) => log.result !== "success").length;
  const gateRadar = gates(gateConfig).map((gate) => { const own = logs.filter((log) => log.gate === gate); return { gate, scans: own.length, accepted: own.filter((log) => log.result === "success").length, issues: own.filter((log) => log.result !== "success").length }; });
  const busiest = [...gateRadar].sort((a, b) => b.scans - a.scans)[0];
  const pulse = !logs.length ? { title: "بانتظار انطلاق الاستقبال", note: "افتح بوابة المسح عند وصول أول ضيف لتبدأ قراءة النبض الحي.", tone: "amber" } : attention > Math.max(2, success * .15) ? { title: "تحتاج عملية الاستقبال مراجعة", note: `${attention} محاولات تحتاج انتباهاً ضمن آخر 100 عملية مسح.`, tone: "rose" } : rate >= 85 ? { title: "الوصول في مراحله الأخيرة", note: "نسبة الحضور مرتفعة؛ جهّز الفريق لمرحلة المتأخرين والاستثناءات.", tone: "emerald" } : { title: "الاستقبال يسير بصورة مستقرة", note: busiest ? `أكثر حركة الآن في ${busiest.gate}: ${busiest.accepted} دخولاً ناجحاً.` : "تتابع المنصة الحضور والبوابات لحظة بلحظة.", tone: "sky" };
  const pulseTone = pulse.tone === "rose" ? "border-rose-400/45 bg-rose-400/[.08] text-rose-200" : pulse.tone === "emerald" ? "border-emerald-400/45 bg-emerald-400/[.08] text-emerald-200" : pulse.tone === "sky" ? "border-sky-400/45 bg-sky-400/[.08] text-sky-100" : "border-amber-400/45 bg-amber-400/[.08] text-amber-100";
  const nextAction = !logs.length ? { label: "فتح بوابة المسح", action: onOpenScanner, icon: ScanLine } : attention ? { label: "مراجعة الضيوف والاستثناءات", action: onOpenGuests, icon: ShieldAlert } : { label: "متابعة بوابات الاستقبال", action: onOpenScanner, icon: DoorOpen };
  const NextIcon = nextAction.icon;
  return <section className="space-y-5" dir="rtl"><div className="relative overflow-hidden rounded-3xl border p-6 md:p-8" style={{ borderColor: `${brandColor}55`, background: `radial-gradient(circle at 90% 0%, ${brandColor}26, transparent 34%), linear-gradient(135deg, #101720, #080b11)` }}><div className="absolute left-0 top-0 h-full w-1" style={{ background: brandColor }} /><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-4"><div className="rounded-2xl p-3" style={{ background: `${brandColor}1d`, color: brandColor }}><Radio size={24} className="animate-pulse" /></div><div><div className="text-xs font-black" style={{ color: brandColor }}>مركز يوم الفعالية</div><h2 className="mt-1 text-2xl font-black text-amber-50">نبض المناسبة الآن</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-400">مكان واحد يوضح للفريق ما يحدث، وما يحتاج تدخلاً، وما الإجراء التالي.</p></div></div><button onClick={nextAction.action} className="inline-flex items-center justify-center gap-2 rounded-xl px-5 py-3 text-sm font-black text-slate-950 shadow-lg" style={{ background: brandColor }}><NextIcon size={17} />{nextAction.label}<ArrowLeft size={15} /></button></div></div>
    <div className={`rounded-2xl border p-5 ${pulseTone}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Activity size={21} /><div><div className="font-black">{pulse.title}</div><div className="mt-1 text-xs leading-6 opacity-80">{pulse.note}</div></div></div><div className="rounded-xl bg-black/20 px-4 py-3 text-center"><div className="text-2xl font-black">{rate}%</div><div className="mt-1 text-[10px] font-bold opacity-70">وصول الضيوف</div></div></div></div>
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/[.08] bg-black/20 p-5"><Users className="text-amber-300" size={19} /><div className="mt-3 text-3xl font-black text-amber-50">{attended}<span className="mr-1 text-base text-slate-500">/ {total}</span></div><div className="mt-1 text-xs text-slate-500">دخلوا فعلياً إلى الفعالية</div></div><div className="rounded-2xl border border-white/[.08] bg-black/20 p-5"><CheckCircle2 className="text-emerald-300" size={19} /><div className="mt-3 text-3xl font-black text-emerald-200">{success}</div><div className="mt-1 text-xs text-slate-500">تسجيلات دخول ناجحة</div></div><div className="rounded-2xl border border-white/[.08] bg-black/20 p-5"><AlertTriangle className={attention ? "text-rose-300" : "text-slate-500"} size={19} /><div className="mt-3 text-3xl font-black text-slate-100">{attention}</div><div className="mt-1 text-xs text-slate-500">محاولات تحتاج مراجعة</div></div></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl border border-white/[.08] bg-black/20 p-5"><div className="flex items-center justify-between"><div><div className="text-xs font-black" style={{ color: brandColor }}>رادار البوابات</div><h3 className="mt-1 font-black text-amber-100">أين يتركز الوصول؟</h3></div><DoorOpen size={20} style={{ color: brandColor }} /></div>{gateRadar.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{gateRadar.map((gate) => <div key={gate.gate} className="rounded-2xl border border-slate-800 bg-white/[.025] p-4"><div className="flex items-center justify-between"><div className="font-bold text-slate-200">{gate.gate}</div><span className={`h-2.5 w-2.5 rounded-full ${gate.issues ? "bg-amber-300" : gate.scans ? "bg-emerald-300" : "bg-slate-600"}`} /></div><div className="mt-4 flex items-end justify-between"><div><div className="text-2xl font-black text-amber-100">{gate.accepted}</div><div className="text-[10px] text-slate-500">دخول ناجح</div></div><div className="text-left text-xs text-slate-400"><div>{gate.scans} مسح</div>{gate.issues ? <div className="mt-1 text-rose-300">{gate.issues} تحتاج مراجعة</div> : <div className="mt-1 text-emerald-300">مستقرة</div>}</div></div></div>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-slate-700 p-6 text-center text-sm text-slate-500">أضف البوابات من إعدادات الفعالية ليظهر رادار الاستقبال هنا.</div>}</section><section className="rounded-3xl border border-white/[.08] bg-black/20 p-5"><div className="flex items-center gap-2"><Clock3 size={18} style={{ color: brandColor }} /><h3 className="font-black text-amber-100">قرار الدقيقة التالية</h3></div><div className="mt-5 space-y-3"><button onClick={onOpenScanner} className="flex w-full items-center justify-between rounded-xl border border-slate-700 p-3 text-right transition hover:border-amber-400/50"><div><div className="text-sm font-bold text-slate-200">متابعة الاستقبال</div><div className="mt-1 text-[11px] text-slate-500">فتح الكاميرا أو إدخال رمز الدعوة يدوياً.</div></div><ScanLine size={17} style={{ color: brandColor }} /></button><button onClick={onOpenGuests} className="flex w-full items-center justify-between rounded-xl border border-slate-700 p-3 text-right transition hover:border-amber-400/50"><div><div className="text-sm font-bold text-slate-200">مراجعة قائمة الضيوف</div><div className="mt-1 text-[11px] text-slate-500">تحقق من المتأخرين والاستثناءات والدعوات.</div></div><Users size={17} style={{ color: brandColor }} /></button></div></section></div></section>;
}
