import { getInvitationTemplate, isInvitationTemplateId, parseInvitationLayout, type InvitationLayoutConfig } from "@/lib/invitationDesign";
import { trpc } from "@/lib/trpc";
import { BookmarkPlus, Check, Loader2, Trash2 } from "lucide-react";
import { useMemo } from "react";
import { toast } from "sonner";
import InvitationTemplatePreview from "./InvitationTemplatePreview";

export type InvitationPresetConfig = { templateId: string; title: string; subtitle: string; brandColor: string; logoUrl: string; backgroundUrl: string; invitationDate: string; invitationVenue: string; invitationDressCode: string; customTemplateName: string; invitationLayout: InvitationLayoutConfig };
type Props = { ceremonyId: number; current: InvitationPresetConfig; onApply: (config: InvitationPresetConfig) => void };

function parsePreset(value: string): InvitationPresetConfig | null { try { const parsed = JSON.parse(value); if (!parsed || typeof parsed !== "object" || !isInvitationTemplateId(parsed.templateId)) return null; return { templateId: parsed.templateId, title: String(parsed.title || ""), subtitle: String(parsed.subtitle || ""), brandColor: String(parsed.brandColor || getInvitationTemplate(parsed.templateId).accent), logoUrl: String(parsed.logoUrl || ""), backgroundUrl: String(parsed.backgroundUrl || ""), invitationDate: String(parsed.invitationDate || ""), invitationVenue: String(parsed.invitationVenue || ""), invitationDressCode: String(parsed.invitationDressCode || ""), customTemplateName: String(parsed.customTemplateName || ""), invitationLayout: { ...parseInvitationLayout(JSON.stringify(parsed.invitationLayout || {})), sourceTemplateId: parsed.templateId } }; } catch { return null; } }

export default function InvitationPresetLibrary({ ceremonyId, current, onApply }: Props) {
  const utils = trpc.useUtils(); const queryInput = useMemo(() => ({ ceremonyId }), [ceremonyId]); const presets = trpc.invitationPresets.list.useQuery(queryInput);
  const save = trpc.invitationPresets.create.useMutation({ onSuccess: () => { toast.success("تم حفظ القالب الجديد ضمن هذه الفعالية"); void utils.invitationPresets.list.invalidate(queryInput); }, onError: (error) => toast.error(error.message || "تعذر حفظ القالب") });
  const remove = trpc.invitationPresets.delete.useMutation({ onSuccess: () => { toast.success("تم حذف القالب المحفوظ"); void utils.invitationPresets.list.invalidate(queryInput); }, onError: (error) => toast.error(error.message || "تعذر حذف القالب") });
  const saveAsNew = () => { const name = window.prompt("اكتب اسماً للقالب الجديد", `${getInvitationTemplate(current.templateId).name} — نسختي`); if (!name?.trim()) return; save.mutate({ ceremonyId, name: name.trim(), sourceTemplateId: current.templateId, config: JSON.stringify(current) }); };
  return <section className="rounded-3xl border border-amber-400/20 bg-[linear-gradient(120deg,rgba(251,191,36,.08),transparent_40%),#10141e] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black text-amber-300"><BookmarkPlus size={16} />ورشة القوالب الخاصة</div><h2 className="mt-2 font-black text-amber-50">عدّل أي قالب ثم احتفظ به باسم جديد</h2><p className="mt-1 text-xs leading-5 text-slate-500">يُحفظ النص والخلفية والألوان والتفاصيل والتخطيط الحر، ويمكن تطبيقه لاحقاً على نفس الفعالية.</p></div><button type="button" onClick={saveAsNew} disabled={save.isPending} className="inline-flex items-center justify-center gap-2 rounded-xl bg-amber-400 px-4 py-3 text-xs font-black text-amber-950 transition hover:bg-amber-300 disabled:opacity-60">{save.isPending ? <Loader2 size={15} className="animate-spin" /> : <BookmarkPlus size={15} />}حفظ تعديلاتي كقالب جديد</button></div>{presets.isLoading ? <div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Loader2 size={14} className="animate-spin" />جارٍ تحميل قوالبك…</div> : presets.data?.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{presets.data.map((preset) => { const config = parsePreset(preset.config); if (!config) return null; return <div key={preset.id} className="group relative overflow-hidden rounded-2xl border border-slate-800 bg-black/20 p-2"><button type="button" onClick={() => { onApply(config); toast.success(`تم تطبيق قالب «${preset.name}»`); }} className="block w-full text-right"><InvitationTemplatePreview templateId={config.templateId} title={config.title} subtitle={config.subtitle} brandColor={config.brandColor} backgroundUrl={config.backgroundUrl} date={config.invitationDate} venue={config.invitationVenue} dressCode={config.invitationDressCode} compact /><div className="mt-2 flex items-center justify-between gap-2 px-1"><span className="truncate text-xs font-black text-amber-100">{preset.name}</span><span className="rounded-full bg-amber-400/10 px-2 py-1 text-[9px] font-bold text-amber-300">تطبيق</span></div></button><button type="button" aria-label={`حذف قالب ${preset.name}`} onClick={() => { if (window.confirm(`حذف قالب «${preset.name}»؟`)) remove.mutate({ id: preset.id, ceremonyId }); }} className="absolute left-3 top-3 rounded-full bg-black/60 p-1.5 text-slate-300 opacity-0 transition hover:bg-rose-500 hover:text-white group-hover:opacity-100"><Trash2 size={13} /></button></div>; })}</div> : <div className="mt-4 rounded-2xl border border-dashed border-slate-700 px-4 py-5 text-center text-xs text-slate-500">لم تحفظ قالباً خاصاً بعد. اختر أي تصميم وعدّل ما تريد ثم اضغط «حفظ تعديلاتي كقالب جديد».</div>}</section>;
}
