import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, CheckCircle2, DoorOpen, Loader2, Radio, ScanLine, Users } from "lucide-react";

function listTokens(value?: string | null) {
  return String(value || "").split(/[,،\n]/).map((item) => item.trim()).filter(Boolean);
}

export default function LiveOperationsPanel({ ceremonyId, gates, brandColor, onOpenScanner }: { ceremonyId: number; gates?: string | null; brandColor: string; onOpenScanner: () => void }) {
  const { data: logs, isLoading } = trpc.scan.logs.useQuery({ limit: 100, ceremonyId }, { refetchInterval: 10000 });
  const successful = logs?.filter((log) => log.result === "success").length ?? 0;
  const duplicates = logs?.filter((log) => log.result === "duplicate").length ?? 0;
  const rejected = logs?.filter((log) => log.result === "invalid" || log.result === "not_found").length ?? 0;
  const latest = logs?.[0];
  const gateList = listTokens(gates);
  const gateActivity = gateList.map((gate) => {
    const gateLogs = logs?.filter((log) => log.gate === gate) ?? [];
    return { gate, scans: gateLogs.length, accepted: gateLogs.filter((log) => log.result === "success").length, latest: gateLogs[0] };
  });

  return <section className="rounded-3xl border p-5 md:p-6" style={{ borderColor: `${brandColor}45`, background: `linear-gradient(135deg, ${brandColor}12, oklch(11% 0.014 250))` }}>
    <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3"><div className="rounded-2xl p-2.5" style={{ background: `${brandColor}20`, color: brandColor }}><Radio size={21} className="animate-pulse" /></div><div><div className="text-xs font-bold" style={{ color: brandColor }}>مركز التشغيل الحي</div><h2 className="mt-1 text-xl font-black text-amber-100">نبض الاستقبال الآن</h2><p className="mt-1 text-sm text-slate-400">تتحدث عمليات المسح تلقائياً كل 10 ثوانٍ لهذه الفعالية فقط.</p></div></div><button onClick={onOpenScanner} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-black text-slate-950" style={{ background: brandColor }}><ScanLine size={17} /> فتح بوابة المسح</button></div>
    <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="rounded-2xl bg-black/25 p-4"><Activity size={18} className="text-sky-300" /><div className="mt-3 text-2xl font-black text-slate-100">{logs?.length ?? 0}</div><div className="mt-1 text-[11px] text-slate-500">كل محاولات المسح</div></div><div className="rounded-2xl bg-black/25 p-4"><CheckCircle2 size={18} className="text-emerald-300" /><div className="mt-3 text-2xl font-black text-emerald-200">{successful}</div><div className="mt-1 text-[11px] text-slate-500">دخول ناجح</div></div><div className="rounded-2xl bg-black/25 p-4"><AlertTriangle size={18} className="text-amber-300" /><div className="mt-3 text-2xl font-black text-amber-200">{duplicates}</div><div className="mt-1 text-[11px] text-slate-500">محاولات مكررة</div></div><div className="rounded-2xl bg-black/25 p-4"><Users size={18} className="text-rose-300" /><div className="mt-3 text-2xl font-black text-rose-200">{rejected}</div><div className="mt-1 text-[11px] text-slate-500">تحقق غير مكتمل</div></div></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_0.8fr]"><div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><div className="text-xs font-bold text-slate-500">آخر إشارة من الاستقبال</div>{isLoading ? <Loader2 className="mt-5 animate-spin text-amber-300" size={20} /> : latest ? <div className="mt-3 flex items-center justify-between gap-3"><div><div className="font-mono text-sm text-slate-200">{latest.qrCode}</div><div className="mt-1 text-xs text-slate-500">{latest.gate ? `${latest.gate} · ` : ""}{new Date(latest.scannedAt).toLocaleTimeString("ar-SA", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</div></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${latest.result === "success" ? "bg-emerald-400/15 text-emerald-300" : latest.result === "duplicate" ? "bg-amber-400/15 text-amber-300" : "bg-rose-400/15 text-rose-300"}`}>{latest.result === "success" ? "دخول ناجح" : latest.result === "duplicate" ? "دخول مكرر" : "تحتاج مراجعة"}</span></div> : <div className="mt-3 text-sm text-slate-500">لم تبدأ عمليات المسح بعد.</div>}</div><div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><DoorOpen size={14} style={{ color: brandColor }} />حالة البوابات</div>{gateActivity.length ? <div className="mt-3 space-y-2">{gateActivity.map((item) => <div key={item.gate} className="flex items-center justify-between rounded-xl bg-white/[0.035] px-3 py-2"><div><div className="text-xs font-bold text-slate-200">{item.gate}</div><div className="mt-0.5 text-[10px] text-slate-500">{item.latest ? `آخر قراءة ${new Date(item.latest.scannedAt).toLocaleTimeString("ar-SA", { hour: "2-digit", minute: "2-digit" })}` : "لا توجد قراءات بعد"}</div></div><div className="text-left"><div className="text-sm font-black text-emerald-200">{item.accepted}</div><div className="text-[10px] text-slate-500">من {item.scans} مسح</div></div></div>)}</div> : <div className="mt-3 text-sm text-slate-500">أضف البوابات من إعدادات الفعالية لتظهر هنا.</div>}</div></div>
  </section>;
}
