import React from "react";
import {
  FileText,
  Smartphone,
  Briefcase,
  Mail,
  Cloud,
  Ticket,
  Video,
  Shield,
  ExternalLink,
  GraduationCap,
  BookOpen,
  Book,
  Library,
  FileCheck,
  PenTool,
  School,
  Calculator,
  Microscope,
  Languages,
  Lightbulb,
  Bus,
  Utensils,
  HeartPulse,
  Wrench,
  Clock,
  Calendar,
  MapPin,
  Building,
  Key,
  Coffee,
  CreditCard,
  Wallet,
  Receipt,
  DollarSign,
  CircleDollarSign,
  Banknote,
  Scale,
  Folder,
  FileSpreadsheet,
  MessageSquare,
  Phone,
  Bell,
  Send,
  Share2,
  Headphones,
  Radio,
  Newspaper,
  Inbox,
  Database,
  Server,
  QrCode,
  Wifi,
  BarChart3,
  PieChart,
  Users,
  UserCheck,
  Settings,
  Lock,
  ShieldCheck,
  Cpu,
  Laptop,
  Globe,
  Layers,
  Download,
  Upload,
  Printer,
  Trophy,
  Award,
  Medal,
  Star,
  Sparkles,
  Compass,
  Flag,
  Activity,
  Dumbbell,
  Music,
  Camera,
  Image,
  Heart,
  Gift,
  HelpCircle,
  Search,
  type LucideProps,
} from "lucide-react";

export const PORTAL_ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  "file-text": FileText,
  "smartphone": Smartphone,
  "briefcase": Briefcase,
  "mail": Mail,
  "cloud": Cloud,
  "ticket": Ticket,
  "video": Video,
  "shield": Shield,
  "link": ExternalLink,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "book": Book,
  "library": Library,
  "file-check": FileCheck,
  "pen-tool": PenTool,
  "school": School,
  "calculator": Calculator,
  "microscope": Microscope,
  "languages": Languages,
  "lightbulb": Lightbulb,
  "bus": Bus,
  "utensils": Utensils,
  "heart-pulse": HeartPulse,
  "wrench": Wrench,
  "clock": Clock,
  "calendar": Calendar,
  "map-pin": MapPin,
  "building": Building,
  "key": Key,
  "coffee": Coffee,
  "credit-card": CreditCard,
  "wallet": Wallet,
  "receipt": Receipt,
  "dollar-sign": DollarSign,
  "circle-dollar-sign": CircleDollarSign,
  "banknote": Banknote,
  "scale": Scale,
  "folder": Folder,
  "file-spreadsheet": FileSpreadsheet,
  "message-square": MessageSquare,
  "phone": Phone,
  "bell": Bell,
  "send": Send,
  "share-2": Share2,
  "headphones": Headphones,
  "radio": Radio,
  "newspaper": Newspaper,
  "inbox": Inbox,
  "database": Database,
  "server": Server,
  "qr-code": QrCode,
  "wifi": Wifi,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  "users": Users,
  "user-check": UserCheck,
  "settings": Settings,
  "lock": Lock,
  "shield-check": ShieldCheck,
  "cpu": Cpu,
  "laptop": Laptop,
  "globe": Globe,
  "layers": Layers,
  "download": Download,
  "upload": Upload,
  "printer": Printer,
  "trophy": Trophy,
  "award": Award,
  "medal": Medal,
  "star": Star,
  "sparkles": Sparkles,
  "compass": Compass,
  "flag": Flag,
  "activity": Activity,
  "dumbbell": Dumbbell,
  "music": Music,
  "camera": Camera,
  "image": Image,
  "heart": Heart,
  "gift": Gift,
  "help-circle": HelpCircle,
  "search": Search,
};

export interface PortalIconProps {
  name: string;
  size?: number;
  className?: string;
}

export function PortalIcon({ name, size = 16, className = "" }: PortalIconProps) {
  const IconComponent = PORTAL_ICON_MAP[name] || ExternalLink;
  return <IconComponent size={size} className={className} />;
}

export function renderPortalIcon(iconName: string, size = 16, className = "") {
  const IconComponent = PORTAL_ICON_MAP[iconName] || ExternalLink;
  return <IconComponent size={size} className={className} />;
}
